
CREATE TABLE lclj_tmp_yzmb(
	[id] [int] PRIMARY key IDENTITY(1,1) NOT NULL,
	[ph] [varchar](16) NULL,
	[tmh] [varchar](9) NULL,
	[zyh] [char](16) NOT NULL,
	[xmdm] [varchar](14) NOT NULL,
	[xmmc] [varchar](100) NOT NULL,
	[lb] [char](4) NOT NULL default('1'),
	[dw] [varchar](10)  NULL,
	[ypdwid] [int]  NULL,
	[ypbzbl] [int]  NULL default(1),
	[sl] [int]  NULL,
	[yplsj] [numeric](18, 4)  NULL,
	[ypcgj] [numeric](18, 4)  NULL,
	[ypyf] [char](4)  NULL,
	[ypyl] [varchar](10)  NULL,
	[yldw] [varchar](10) NULL,
	[yytj] [varchar](8)  NULL,
	[yplb] [char](10)  NULL,
	[jcmd] [varchar](100) NULL,
	[tzbz] [bit]  NULL,
	[zfbz] [bit]  NULL,
	[zxbz] [bit]  NULL,
	[fzbz] [int] NULL,
	[tzrq] [datetime] NULL,
	[tzry] [char](4) NULL,
	[zfrq] [datetime] NULL,
	[zfry] [char](4) NULL,
	[zxrq] [datetime] NULL,
	[zxry] [char](4) NULL,
	[xgrq] [datetime] NULL,
	[xgry] [char](4) NULL,
	[czks] [char](4)  NULL,
	[kdks] [char](4)  NULL,
	[kdrq] [datetime] DEFAULT (getdate()),
	[kdys] [char](4)  NULL,
	[yzrq] [datetime] NULL,
	[yzsx] [char](4)  NULL DEFAULT ('³¤ÆÚ'),
	[shbz] [bit] NULL,
	[shry] [char](4) NULL,
	[jcbw] [varchar](50) NULL,
	[jcff] [varchar](50) NULL,
	[ypkcbz] [bit] NULL,
	[czys] [varchar](4) NULL,
	[gg] [varchar](50) NULL,
	[fzph] [varchar](20)  NULL,
	[bz] [varchar](100)  NULL,
	[jyyb] [varchar](10)  NULL,
	[jyflbh] [varchar](20) NULL,
	[xh] [int]  NULL,
	[xyzbz] [bit] NULL
)