object frm_zxypyz: Tfrm_zxypyz
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = #21307#22065#25191#34892
  ClientHeight = 590
  ClientWidth = 883
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = #23435#20307
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poMainFormCenter
  Scaled = False
  ShowHint = True
  OnCloseQuery = FormCloseQuery
  OnKeyPress = FormKeyPress
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 15
  object PageControl1: TPageControl
    Left = 0
    Top = 57
    Width = 883
    Height = 533
    ActivePage = TabSheet1
    Align = alClient
    TabOrder = 1
    object TabSheet1: TTabSheet
      Caption = #21307#22065#25191#34892
      object groupbox8: TPanel
        Left = 0
        Top = 0
        Width = 193
        Height = 482
        Align = alLeft
        BevelInner = bvLowered
        TabOrder = 0
        object Panel8: TPanel
          Left = 2
          Top = 355
          Width = 189
          Height = 125
          Align = alBottom
          BevelInner = bvLowered
          TabOrder = 0
          object Button4: TButton
            Left = 17
            Top = 95
            Width = 137
            Height = 25
            Caption = #36873#25321#30830#35748
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
            OnClick = Button4Click
          end
          object Panel4: TPanel
            Left = 2
            Top = 2
            Width = 185
            Height = 87
            Align = alTop
            TabOrder = 1
            object Shape1: TShape
              AlignWithMargins = True
              Left = 1
              Top = 30
              Width = 178
              Height = 1
              Brush.Style = bsVertical
              Shape = stRoundRect
            end
            object cxCheckBox3: TcxCheckBox
              Left = 6
              Top = 36
              Caption = #33647#21697
              ParentFont = False
              State = cbsChecked
              Style.Font.Charset = ANSI_CHARSET
              Style.Font.Color = clWindowText
              Style.Font.Height = -16
              Style.Font.Name = #23435#20307
              Style.Font.Style = []
              Style.IsFontAssigned = True
              TabOrder = 0
              OnMouseDown = cxCheckBox7MouseDown
              Width = 58
            end
            object cxCheckBox6: TcxCheckBox
              Left = 68
              Top = 63
              Caption = #26816#26597
              ParentFont = False
              State = cbsChecked
              Style.Font.Charset = ANSI_CHARSET
              Style.Font.Color = clWindowText
              Style.Font.Height = -16
              Style.Font.Name = #23435#20307
              Style.Font.Style = []
              Style.IsFontAssigned = True
              TabOrder = 1
              OnMouseDown = cxCheckBox7MouseDown
              Width = 57
            end
            object cxCheckBox5: TcxCheckBox
              Left = 6
              Top = 62
              Caption = #27835#30103
              ParentFont = False
              State = cbsChecked
              Style.Font.Charset = ANSI_CHARSET
              Style.Font.Color = clWindowText
              Style.Font.Height = -16
              Style.Font.Name = #23435#20307
              Style.Font.Style = []
              Style.IsFontAssigned = True
              TabOrder = 2
              OnMouseDown = cxCheckBox7MouseDown
              Width = 56
            end
            object cxCheckBox4: TcxCheckBox
              Left = 67
              Top = 36
              Caption = #26448#26009
              ParentFont = False
              State = cbsChecked
              Style.Font.Charset = ANSI_CHARSET
              Style.Font.Color = clWindowText
              Style.Font.Height = -16
              Style.Font.Name = #23435#20307
              Style.Font.Style = []
              Style.IsFontAssigned = True
              TabOrder = 3
              OnMouseDown = cxCheckBox7MouseDown
              Width = 58
            end
            object cxCheckBox7: TcxCheckBox
              Left = 126
              Top = 62
              Caption = #26816#39564
              ParentFont = False
              State = cbsChecked
              Style.Font.Charset = ANSI_CHARSET
              Style.Font.Color = clWindowText
              Style.Font.Height = -16
              Style.Font.Name = #23435#20307
              Style.Font.Style = []
              Style.IsFontAssigned = True
              TabOrder = 4
              OnMouseDown = cxCheckBox7MouseDown
              Width = 57
            end
            object cxCheckBox1: TcxCheckBox
              Left = 7
              Top = 5
              Caption = #38271#26399
              ParentFont = False
              State = cbsChecked
              Style.Font.Charset = ANSI_CHARSET
              Style.Font.Color = clBlue
              Style.Font.Height = -16
              Style.Font.Name = #23435#20307
              Style.Font.Style = []
              Style.IsFontAssigned = True
              TabOrder = 5
              OnMouseDown = cxCheckBox7MouseDown
              Width = 58
            end
            object cxCheckBox2: TcxCheckBox
              Left = 67
              Top = 5
              Caption = #20020#26102
              ParentFont = False
              State = cbsChecked
              Style.Font.Charset = ANSI_CHARSET
              Style.Font.Color = clBlue
              Style.Font.Height = -16
              Style.Font.Name = #23435#20307
              Style.Font.Style = []
              Style.IsFontAssigned = True
              TabOrder = 6
              OnMouseDown = cxCheckBox7MouseDown
              Width = 58
            end
          end
        end
        object DBGridEh1: TDBGridEh
          Left = 2
          Top = 2
          Width = 189
          Height = 315
          Align = alClient
          DataSource = ds_brxx
          Flat = True
          FooterColor = clWindow
          FooterFont.Charset = ANSI_CHARSET
          FooterFont.Color = clWindowText
          FooterFont.Height = -15
          FooterFont.Name = #23435#20307
          FooterFont.Style = []
          Options = [dgTitles, dgIndicator, dgColumnResize, dgColLines, dgRowLines, dgTabs, dgRowSelect, dgConfirmDelete, dgCancelOnExit]
          ReadOnly = True
          TabOrder = 1
          TitleFont.Charset = ANSI_CHARSET
          TitleFont.Color = clWindowText
          TitleFont.Height = -15
          TitleFont.Name = #23435#20307
          TitleFont.Style = []
          OnKeyPress = DBGridEh1KeyPress
          OnMouseDown = DBGridEh1MouseDown
          Columns = <
            item
              EditButtons = <>
              FieldName = 'xz'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #36873#25321
              Width = 35
            end
            item
              EditButtons = <>
              FieldName = 'bch'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #24202#21495
              Width = 44
            end
            item
              EditButtons = <>
              FieldName = 'brxm'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #22995#21517
              Width = 75
            end>
        end
        object Panel3: TPanel
          Left = 2
          Top = 317
          Width = 189
          Height = 38
          Align = alBottom
          TabOrder = 2
          object Button1: TButton
            Left = 14
            Top = 7
            Width = 63
            Height = 25
            Caption = #20840#37096#36873#25321
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlue
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 0
            OnClick = Button1Click
          end
          object Button3: TButton
            Left = 103
            Top = 7
            Width = 66
            Height = 25
            Caption = #20840#37096#21462#28040
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 1
            OnClick = Button3Click
          end
        end
      end
      object groupbox2: TPanel
        Left = 193
        Top = 0
        Width = 682
        Height = 482
        Align = alClient
        TabOrder = 1
        object Panel5: TPanel
          Left = 1
          Top = 1
          Width = 680
          Height = 32
          Align = alTop
          BevelInner = bvLowered
          TabOrder = 0
          object Label4: TLabel
            Left = 389
            Top = 9
            Width = 38
            Height = 15
            Caption = #20313#39069':'
            Visible = False
          end
          object Label7: TLabel
            Left = 11
            Top = 10
            Width = 68
            Height = 15
            Caption = #25191#34892#26102#38388':'
          end
          object Label8: TLabel
            Left = 224
            Top = 9
            Width = 15
            Height = 15
            Caption = #21040
          end
          object DBEdit3: TDBEdit
            Left = 78
            Top = 7
            Width = 138
            Height = 21
            Color = clSkyBlue
            Ctl3D = False
            DataField = 'kssj'
            DataSource = ds_xzzyyz
            ParentCtl3D = False
            ReadOnly = True
            TabOrder = 0
          end
          object DBEdit4: TDBEdit
            Left = 245
            Top = 7
            Width = 138
            Height = 21
            Color = clSkyBlue
            Ctl3D = False
            DataField = 'yjjssj'
            DataSource = ds_xzzyyz
            ParentCtl3D = False
            ReadOnly = True
            TabOrder = 1
          end
          object DBEdit1: TDBEdit
            Left = 433
            Top = 5
            Width = 88
            Height = 21
            Color = clSkyBlue
            Ctl3D = False
            DataField = 'kyje'
            DataSource = ds_jbxx
            ParentCtl3D = False
            ReadOnly = True
            TabOrder = 2
            Visible = False
          end
          object bt_zxjg: TcxButton
            Left = 595
            Top = 5
            Width = 73
            Height = 23
            Caption = #25191#34892#32467#26524
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 3
            OnClick = bt_zxjgClick
          end
        end
        object Panel6: TPanel
          Left = 1
          Top = 447
          Width = 680
          Height = 34
          Align = alBottom
          BevelInner = bvLowered
          TabOrder = 1
          object cxButton1: TcxButton
            Left = 369
            Top = 6
            Width = 68
            Height = 23
            Caption = #36755#28082#21333'(&P)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 0
            OnClick = cxButton1Click
          end
          object cxButton6: TcxButton
            Left = 598
            Top = 6
            Width = 75
            Height = 23
            Caption = #36820#22238'(&B)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 1
            OnClick = cxButton6Click
          end
          object cxButton3: TcxButton
            Left = 441
            Top = 6
            Width = 78
            Height = 23
            Caption = #25191#34892#35760#24405'(&T)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 2
            OnClick = cxButton3Click
          end
          object bt_jf: TcxButton
            Left = 154
            Top = 6
            Width = 73
            Height = 22
            Caption = #25191#34892#21307#22065
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 3
            OnClick = bt_jfClick
          end
          object b_move: TcxButton
            Left = 5
            Top = 6
            Width = 91
            Height = 23
            Caption = #31227#38500#24050#35760#36153#21307#22065
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 4
            OnClick = b_moveClick
          end
          object cxButton5: TcxButton
            Left = 283
            Top = 6
            Width = 80
            Height = 23
            Caption = #33647#21697#25209#37327#36890#30693
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -12
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            TabOrder = 5
            OnClick = cxButton5Click
          end
        end
        object cxGrid2: TcxGrid
          Left = 1
          Top = 33
          Width = 680
          Height = 414
          Hint = #40736#26631#21452#20987#31227#20986#19981#24819#25191#34892#21307#22065
          HelpType = htKeyword
          HelpKeyword = 'H'
          Align = alClient
          TabOrder = 2
          LookAndFeel.Kind = lfOffice11
          LookAndFeel.NativeStyle = False
          RootLevelOptions.DetailFrameWidth = 1
          object cxGridDBTableView2: TcxGridDBTableView
            OnDblClick = cxGridDBTableView2DblClick
            NavigatorButtons.ConfirmDelete = False
            NavigatorButtons.First.Visible = True
            NavigatorButtons.PriorPage.Visible = True
            NavigatorButtons.Prior.Visible = True
            NavigatorButtons.Next.Visible = True
            NavigatorButtons.NextPage.Visible = True
            NavigatorButtons.Last.Visible = True
            NavigatorButtons.Insert.Visible = True
            NavigatorButtons.Delete.Visible = True
            NavigatorButtons.Edit.Visible = True
            NavigatorButtons.Post.Visible = True
            NavigatorButtons.Cancel.Visible = True
            NavigatorButtons.Refresh.Visible = True
            NavigatorButtons.SaveBookmark.Visible = True
            NavigatorButtons.GotoBookmark.Visible = True
            NavigatorButtons.Filter.Visible = True
            OnCustomDrawCell = cxGridDBTableView2CustomDrawCell
            BackgroundBitmaps.Group.Data = {
              B62B0000424DB62B00000000000036000000280000004D000000300000000100
              180000000000802B0000D60E0000D60E00000000000000000000DDDDDDDDDDDD
              EEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCC
              CCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDD
              DDDDDDDDDDDDDDCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCC99BBBBBBCCCCCCCCCC99CCCCCCCCCC
              CC00DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEE
              DDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCC
              CCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCC
              CCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBB
              BBBBCCCC99CCCCCCCCCC99CCCCCCBBBBBB00CCCCCCDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDD
              DDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBB
              BBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCC
              CCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCC00DDDDDDCCCCCC
              CCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
              CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
              DDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
              CCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
              DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCC99CCCC
              CC00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEE
              DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEE
              EEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBBBBBBBCCCC99
              BBBBBBCCCCCCBBBBBB00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEE
              EEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCC
              CCCCCCCCCCCCCCCC99DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCC
              CCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCBBBBBBBBBBBBCCCCCCBBBBBBCCCCCC00DDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCC
              CCCCCCCCCCCCCCCCCCDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDD
              DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCBBBBBBCCCCCCCCCC9900DDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCC
              CCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEE
              DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEE
              EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCC
              CCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCC
              CC00CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDD
              DDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
              EEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
              DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCBBBBBB
              CCCCCCCCCCCCCCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBB
              BBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEE
              EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
              EEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
              CCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCBBBBBBCCCCCCBBBBBBCCCC99CCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDCCCC
              CCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
              DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDD
              EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
              DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
              DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC99CCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCC00CCCCCCCCCCCC
              DDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCC
              CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEE
              EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEE
              DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCC
              CCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCC
              CC00CCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBB
              CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEE
              EEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDCCCCCCCCCCCCCCCCCC
              CCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEE
              EEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBB
              BBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCDDDDDD00CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
              CCCCBBBBBBCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
              EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDD
              DDDDDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDD
              EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDD
              DDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCC
              CCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDD
              EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEE
              EEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDD
              DDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCC
              CCCCCCDDDDDDCCCC99CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCC
              CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDDDDDDD
              DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEE
              EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
              EEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDD
              DDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDD
              DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCC99CCCCCCDDDDDDCCCCCCDDDDDD
              DDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDD
              DD00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              EEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCC
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEE
              EEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDD
              DDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDD
              DDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEE
              EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDD
              DDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD
              EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC
              99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDDCCCCCCDDDDDDDDDD
              DDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
              EEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDEEEEEEEEEEEEEEEE
              EEDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDD
              DDCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDD00DDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCC
              CCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDD
              EEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDD
              DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCDDDDDD
              CCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DD00DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBB
              BBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDD
              DDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCC
              CCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCC
              CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
              CCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
              CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD00DDDDDDCCCCCCDDDDDDCCCCCCCCCC
              CCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDD
              DDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
              CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDD00CCCCCCCCCCCC
              CCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDD
              DDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
              EEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
              DD00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCC
              CCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCC
              CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
              DDDDDDDDDDDDCCCCCC00CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDD
              DDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
              DDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDD
              DDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
              EEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCC00CCCCCCCCCCCCDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
              EEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCDDDDDD
              DDDDDDDDDDDDCCCCCCDDDDDDCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCC
              CCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDD
              DDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEE
              EEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCC00CCCCCCCCCCCC
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEE
              EEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCC
              CCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBB
              BBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDD
              DDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
              CC00DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCC
              CCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCC
              CCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
              DDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCC
              CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDCCCCCC00DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDD
              DDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDD
              DDDDDDCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDD
              DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCDDDDDDDDDDDDEE
              EEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
              CCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCC
              CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
              EEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDD
              DDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCC
              CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDDDDD
              DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDCCCCCC
              CCCCCCCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEE
              EEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCC
              CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
              CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
              DDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCC
              CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CC00CCCCCCDDDDDDCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCC
              DDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDD
              DDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDD
              DDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCC
              CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCC
              CCCCCCCC99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCBBBBBB
              CCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBB
              BBBBBBBBBBCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEE
              DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDD
              DDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDD
              DDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
              DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC
              CCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDCCCCCCCCCC
              CCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDEEEEEEDDDDDDEEEEEEDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              EEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDD
              DDCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCDDDD
              DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEE
              EEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
              EEEEDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
              BBBBBBCCCCCCBBBBBBCCCCCCBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              CC00DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBBBB
              CCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEE
              EEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDD
              DDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE
              DDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCC
              CCCCCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCC
              DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCC
              CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDD
              DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDD
              DDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
              EEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCDDDD
              DDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCC
              CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDEEEEEEEEEEEEDDDD
              DDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEE
              EEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEE
              EEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDD
              CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDD00DDDDDDDDDDDD
              DDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDD
              DDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEE
              EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDD
              DDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC
              CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEE
              EE00DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEE
              EEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDD
              DDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
              CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCC
              CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
              DDDDDDEEEEEEDDDDDD00DDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDD
              DDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              EEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
              EEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDD
              DDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDD
              DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEE
              EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCC
              CCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDDEEEEEEDDDDDDEEEE
              EEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
              EEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
              DDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEE
              EEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDD
              EEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEE
              EEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDD
              DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEE
              EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDEEEEEEDDDD
              DDADDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEE
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDD
              DDEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEE
              EEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDD
              EEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDD
              DDDDDDDDDDDDEEEEEEA4EEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDD
              DDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEE
              EEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEE
              EEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEE
              EEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDDD
              DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE16EEEEEEEEEEEEEEEEEEEEEEEEDDDD
              DDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
              EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEE
              DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDD
              DDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEE
              EEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE
              EEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
              CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEE00}
            DataController.DataSource = ds_xzzyyz
            DataController.Summary.DefaultGroupSummaryItems = <>
            DataController.Summary.FooterSummaryItems = <>
            DataController.Summary.SummaryGroups = <>
            OptionsCustomize.ColumnMoving = False
            OptionsData.CancelOnExit = False
            OptionsData.Deleting = False
            OptionsData.DeletingConfirmation = False
            OptionsData.Editing = False
            OptionsData.Inserting = False
            OptionsSelection.CellSelect = False
            OptionsSelection.MultiSelect = True
            object cxGridDByzsx: TcxGridDBColumn
              Caption = #21307#22065#23646#24615
              DataBinding.FieldName = 'yzsx'
              HeaderAlignmentHorz = taCenter
              SortIndex = 1
              SortOrder = soDescending
              Width = 63
            end
            object cxGridDBColumn1: TcxGridDBColumn
              Caption = #39033#30446#21517#31216
              DataBinding.FieldName = 'xmmc'
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              Options.Filtering = False
              Width = 221
            end
            object cxGridDBColumn2: TcxGridDBColumn
              Caption = #25968#37327
              DataBinding.FieldName = 'sl'
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              Options.Filtering = False
              Width = 48
            end
            object cxGridDBColumn3: TcxGridDBColumn
              Caption = #21333#20301
              DataBinding.FieldName = 'dw'
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              Options.Filtering = False
              Width = 45
            end
            object cxGridDBColumn5: TcxGridDBColumn
              Caption = #29992#37327
              DataBinding.FieldName = 'ypyl'
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              Options.Filtering = False
              Width = 44
            end
            object cxGridDBColumn4: TcxGridDBColumn
              Caption = #29992#27861
              DataBinding.FieldName = 'ypyf'
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              Options.Filtering = False
              Width = 40
            end
            object cxGridDBColumn6: TcxGridDBColumn
              Caption = #21333#20301
              DataBinding.FieldName = 'yldw'
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              Options.Filtering = False
              Width = 50
            end
            object cxGridDBColumn7: TcxGridDBColumn
              Caption = #25191#34892#31185#23460
              DataBinding.FieldName = 'czksmc'
              Visible = False
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              Options.Filtering = False
              Width = 64
            end
            object cxGridDBColumn8: TcxGridDBColumn
              Caption = #21307#22065#31867#21035
              DataBinding.FieldName = 'lb'
              Visible = False
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              SortIndex = 0
              SortOrder = soAscending
              Width = 68
            end
            object cxGridDBColumn9: TcxGridDBColumn
              Caption = #24320#21333#21307#29983
              DataBinding.FieldName = 'kdys'
              Visible = False
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              Options.Filtering = False
              Width = 64
            end
            object cxGridDBColumn10: TcxGridDBColumn
              Caption = #36884#24452
              DataBinding.FieldName = 'yytj'
              HeaderAlignmentHorz = taCenter
              Options.Editing = False
              Options.Filtering = False
              Width = 40
            end
            object cxGridDBColumn12: TcxGridDBColumn
              Caption = #24211#23384#19981#36275
              DataBinding.FieldName = 'ypkcbz'
              PropertiesClassName = 'TcxCheckBoxProperties'
              HeaderAlignmentHorz = taCenter
              Options.Filtering = False
              SortIndex = 2
              SortOrder = soDescending
              Width = 82
            end
            object cxGridDBTableView2DBzhzxsj: TcxGridDBColumn
              DataBinding.FieldName = 'zhzxsj'
              Visible = False
            end
            object cxGridDBTablebrxm: TcxGridDBColumn
              Caption = #22995#21517
              DataBinding.FieldName = 'brxm'
              Visible = False
              GroupIndex = 0
            end
            object cxGridDBTableView2DBph: TcxGridDBColumn
              Caption = #21307#22065#25209#21495
              DataBinding.FieldName = 'kdrq'
              Visible = False
              GroupIndex = 1
              HeaderAlignmentHorz = taCenter
              SortIndex = 3
              SortOrder = soAscending
            end
            object cxGridDBTableView2drcs: TcxGridDBColumn
              Caption = #24403#26085#25191#34892#27425#25968
              DataBinding.FieldName = 'drzxcs'
              Visible = False
              HeaderAlignmentHorz = taRightJustify
            end
          end
          object cxGridLevel1: TcxGridLevel
            GridView = cxGridDBTableView2
            Options.DetailFrameWidth = 0
          end
        end
      end
      object Panel1: TPanel
        Left = 0
        Top = 482
        Width = 875
        Height = 21
        Align = alBottom
        BevelInner = bvLowered
        TabOrder = 2
        object Label5: TLabel
          Left = 41
          Top = 4
          Width = 105
          Height = 15
          Caption = #24403#22825#24050#25191#34892#21307#22065
        end
        object Label1: TLabel
          Left = 10
          Top = 6
          Width = 25
          Height = 9
          AutoSize = False
          Color = 8421440
          ParentColor = False
        end
        object ProgressBar1: TProgressBar
          Left = 194
          Top = 2
          Width = 679
          Height = 17
          Align = alRight
          Step = 1
          TabOrder = 0
        end
        object cxLabel1: TcxLabel
          Left = 398
          Top = 3
          Caption = #25968#25454#20934#22791#36827#24230'(0%)'
          ParentFont = False
          Properties.Alignment.Horz = taCenter
          Properties.Alignment.Vert = taVCenter
          Style.Font.Charset = ANSI_CHARSET
          Style.Font.Color = clLime
          Style.Font.Height = -15
          Style.Font.Name = #23435#20307
          Style.Font.Style = []
          Style.TextColor = clFuchsia
          Style.TransparentBorder = False
          Style.IsFontAssigned = True
          StyleHot.BorderStyle = ebsNone
          Transparent = True
        end
      end
    end
    object TabSheet2: TTabSheet
      Caption = #36153#29992#26126#32454
      ImageIndex = 1
      OnShow = TabSheet2Show
      object cxGrid1: TcxGrid
        Left = 0
        Top = 0
        Width = 875
        Height = 462
        Align = alClient
        TabOrder = 0
        LookAndFeel.Kind = lfStandard
        object cxGrid1DBTableView1: TcxGridDBTableView
          NavigatorButtons.ConfirmDelete = False
          OnCustomDrawCell = cxGrid1DBTableView1CustomDrawCell
          DataController.DataSource = ds_fymx
          DataController.Summary.DefaultGroupSummaryItems = <>
          DataController.Summary.FooterSummaryItems = <>
          DataController.Summary.SummaryGroups = <>
          OptionsCustomize.ColumnMoving = False
          OptionsData.Deleting = False
          OptionsData.DeletingConfirmation = False
          OptionsData.Inserting = False
          OptionsSelection.MultiSelect = True
          OptionsView.GroupByBox = False
          object cxGrid1DBTableView1tfbz: TcxGridDBColumn
            Caption = #36873#25321
            DataBinding.FieldName = 'tfbz'
            PropertiesClassName = 'TcxCheckBoxProperties'
            Width = 63
          end
          object cxGrid1DBTableView1sfrq: TcxGridDBColumn
            Caption = #25910#36153#26085#26399
            DataBinding.FieldName = 'sfrq'
            Options.Editing = False
            Options.Grouping = False
            Width = 152
          end
          object cxGrid1DBTableView1fymc: TcxGridDBColumn
            Caption = #36153#29992#21517#31216
            DataBinding.FieldName = 'fymc'
            Options.Editing = False
            Options.Grouping = False
            Width = 191
          end
          object cxGrid1DBTableView1dw: TcxGridDBColumn
            Caption = #21333#20301
            DataBinding.FieldName = 'dw'
            Options.Editing = False
            Width = 61
          end
          object cxGrid1DBTableView1fyje: TcxGridDBColumn
            Caption = #36153#29992#37329#39069
            DataBinding.FieldName = 'fyje'
            Options.Editing = False
            Options.Grouping = False
            Width = 81
          end
          object cxGrid1DBTableView1zfje: TcxGridDBColumn
            Caption = #24320#21333#21307#29983
            DataBinding.FieldName = 'kdys'
            Options.Editing = False
            Options.Grouping = False
            Width = 90
          end
          object cxGrid1DBTableView1czks: TcxGridDBColumn
            Caption = #22788#29702#31185#23460
            DataBinding.FieldName = 'czks'
            Options.Editing = False
            Width = 97
          end
          object cxGrid1DBTableView1mc: TcxGridDBColumn
            Caption = #25805#20316#21592
            DataBinding.FieldName = 'sfczy'
            Options.Editing = False
            Options.Grouping = False
            Width = 80
          end
          object cxGrid1DBTableView1yjqrbz: TcxGridDBColumn
            Caption = #21307#25216#30830#35748
            DataBinding.FieldName = 'yjqrbz'
            HeaderAlignmentHorz = taCenter
            Options.Editing = False
            Width = 60
          end
        end
        object cxGrid1Level1: TcxGridLevel
          GridView = cxGrid1DBTableView1
        end
      end
      object Panel2: TPanel
        Left = 0
        Top = 462
        Width = 875
        Height = 41
        Align = alBottom
        TabOrder = 1
        object cxButton4: TcxButton
          Left = 607
          Top = 11
          Width = 139
          Height = 23
          Caption = #21307#25216#30830#35748#21333#25171#21360
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          OnClick = cxButton4Click
        end
      end
      object QuickRep1: TQuickRep
        Left = -4
        Top = 72
        Width = 816
        Height = 336
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        DataSet = qry_yjddy
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = #23435#20307
        Font.Style = []
        Functions.Strings = (
          'PAGENUMBER'
          'COLUMNNUMBER'
          'REPORTTITLE')
        Functions.DATA = (
          '0'
          '0'
          #39#39)
        Options = [FirstPageHeader, LastPageFooter]
        Page.Columns = 1
        Page.Orientation = poPortrait
        Page.PaperSize = Custom
        Page.Values = (
          100.000000000000000000
          888.000000000000000000
          100.000000000000000000
          2159.000000000000000000
          100.000000000000000000
          100.000000000000000000
          0.000000000000000000)
        PrinterSettings.Copies = 1
        PrinterSettings.OutputBin = Auto
        PrinterSettings.Duplex = False
        PrinterSettings.FirstPage = 0
        PrinterSettings.LastPage = 0
        PrinterSettings.UseStandardprinter = False
        PrinterSettings.UseCustomBinCode = False
        PrinterSettings.CustomBinCode = 0
        PrinterSettings.ExtendedDuplex = 0
        PrinterSettings.UseCustomPaperCode = False
        PrinterSettings.CustomPaperCode = 0
        PrinterSettings.PrintMetaFile = False
        PrinterSettings.PrintQuality = 0
        PrinterSettings.Collate = 0
        PrinterSettings.ColorOption = 0
        PrintIfEmpty = True
        SnapToGrid = True
        Units = MM
        Zoom = 100
        PrevFormStyle = fsStayOnTop
        PreviewInitialState = wsMaximized
        PrevShowThumbs = False
        PrevShowSearch = False
        PrevInitialZoom = qrZoomToFit
        object QRBand4: TQRBand
          Left = 38
          Top = 165
          Width = 740
          Height = 32
          Frame.Color = clBlack
          Frame.DrawTop = True
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          AlignToBottom = False
          Color = clWhite
          TransparentBand = False
          ForceNewColumn = False
          ForceNewPage = False
          Size.Values = (
            84.666666666666670000
            1957.916666666667000000)
          PreCaluculateBandHeight = False
          KeepOnOnePage = False
          BandType = rbGroupFooter
        end
        object DetailBand1: TQRBand
          Left = 38
          Top = 144
          Width = 740
          Height = 21
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          AlignToBottom = False
          Color = clWhite
          TransparentBand = False
          ForceNewColumn = False
          ForceNewPage = False
          Size.Values = (
            55.562500000000000000
            1957.916666666667000000)
          PreCaluculateBandHeight = False
          KeepOnOnePage = False
          BandType = rbDetail
          object QRDBText1: TQRDBText
            Left = 298
            Top = 2
            Width = 225
            Height = 15
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              39.687500000000000000
              788.458333333333400000
              5.291666666666667000
              595.312500000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Color = clWhite
            DataSet = qry_yjddy
            DataField = 'fymc'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 10
          end
          object QRDBText2: TQRDBText
            Left = 534
            Top = 1
            Width = 100
            Height = 15
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              39.687500000000000000
              1412.875000000000000000
              2.645833333333333000
              264.583333333333400000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Color = clWhite
            DataSet = qry_yjddy
            DataField = 'dw'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 10
          end
          object QRDBText4: TQRDBText
            Left = 643
            Top = 3
            Width = 92
            Height = 15
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              39.687500000000000000
              1701.270833333333000000
              7.937500000000000000
              243.416666666666700000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Color = clWhite
            DataSet = qry_yjddy
            DataField = 'fyje'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 10
          end
          object QRDBText5: TQRDBText
            Left = 123
            Top = 0
            Width = 162
            Height = 15
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              39.687500000000000000
              325.437500000000000000
              0.000000000000000000
              428.625000000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Color = clWhite
            DataSet = qry_yjddy
            DataField = 'sfrq'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 10
          end
          object QRDBText6: TQRDBText
            Left = 5
            Top = 1
            Width = 116
            Height = 15
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              39.687500000000000000
              13.229166666666670000
              2.645833333333333000
              306.916666666666700000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Color = clWhite
            DataSet = qry_yjddy
            DataField = 'id'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = #23435#20307
            Font.Style = [fsBold]
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 10
          end
        end
        object ColumnHeaderBand1: TQRBand
          Left = 38
          Top = 121
          Width = 740
          Height = 23
          Frame.Color = clBlack
          Frame.DrawTop = True
          Frame.DrawBottom = True
          Frame.DrawLeft = False
          Frame.DrawRight = False
          AlignToBottom = False
          Color = clWhite
          TransparentBand = False
          ForceNewColumn = False
          ForceNewPage = False
          Size.Values = (
            60.854166666666670000
            1957.916666666667000000)
          PreCaluculateBandHeight = False
          KeepOnOnePage = False
          BandType = rbColumnHeader
          object QRLabel19: TQRLabel
            Left = 364
            Top = 2
            Width = 61
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              963.083333333333300000
              5.291666666666667000
              161.395833333333300000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #30003#35831#39033#30446
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRLabel20: TQRLabel
            Left = 562
            Top = 2
            Width = 31
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              1486.958333333333000000
              5.291666666666667000
              82.020833333333330000)
            Alignment = taRightJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #21333#20301
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRLabel23: TQRLabel
            Left = 667
            Top = 4
            Width = 31
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              1764.770833333333000000
              10.583333333333330000
              82.020833333333330000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #37329#39069
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRLabel2: TQRLabel
            Left = 169
            Top = 2
            Width = 61
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              447.145833333333300000
              5.291666666666667000
              161.395833333333300000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #35760#36153#26102#38388
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRLabel3: TQRLabel
            Left = 17
            Top = 2
            Width = 46
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              44.979166666666670000
              5.291666666666667000
              121.708333333333300000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #27969#27700#21495
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
        end
        object PageHeaderBand1: TQRBand
          Left = 38
          Top = 38
          Width = 740
          Height = 83
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          AlignToBottom = False
          Color = clWhite
          TransparentBand = False
          ForceNewColumn = False
          ForceNewPage = False
          Size.Values = (
            219.604166666666700000
            1957.916666666667000000)
          PreCaluculateBandHeight = False
          KeepOnOnePage = False
          BandType = rbPageHeader
          object QRLabel22: TQRLabel
            Left = 22
            Top = 4
            Width = 683
            Height = 27
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              71.437500000000000000
              58.208333333333320000
              10.583333333333330000
              1807.104166666667000000)
            Alignment = taCenter
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Caption = #21307#25216#30830#35748#21333
            Color = clWhite
            Font.Charset = ANSI_CHARSET
            Font.Color = clNavy
            Font.Height = -21
            Font.Name = #23435#20307
            Font.Style = [fsBold]
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 16
          end
          object QRLabel18: TQRLabel
            Left = 20
            Top = 40
            Width = 69
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              52.916666666666670000
              105.833333333333300000
              182.562500000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #22788#32622#31185#23460':'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRLabel17: TQRLabel
            Left = 223
            Top = 40
            Width = 69
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              590.020833333333300000
              105.833333333333300000
              182.562500000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #25171#21360#26085#26399':'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRLabel24: TQRLabel
            Left = 500
            Top = 40
            Width = 54
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              1322.916666666667000000
              105.833333333333300000
              142.875000000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #25805#20316#21592':'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRDBText14: TQRDBText
            Left = 576
            Top = 40
            Width = 123
            Height = 15
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              39.687500000000000000
              1524.000000000000000000
              105.833333333333300000
              325.437500000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Color = clWhite
            DataSet = qry_fymx
            DataField = 'sfczy'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 10
          end
          object QRLabel13: TQRLabel
            Left = 22
            Top = 61
            Width = 54
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              58.208333333333330000
              161.395833333333300000
              142.875000000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #20303#38498#21495':'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRDBText12: TQRDBText
            Left = 95
            Top = 61
            Width = 100
            Height = 15
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              39.687500000000000000
              251.354166666666700000
              161.395833333333300000
              264.583333333333300000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Color = clWhite
            DataSet = sp_brxx
            DataField = 'tmh'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 10
          end
          object QRLabel1: TQRLabel
            Left = 220
            Top = 61
            Width = 39
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              582.083333333333300000
              161.395833333333300000
              103.187500000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #22995#21517':'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRDBText13: TQRDBText
            Left = 265
            Top = 61
            Width = 102
            Height = 15
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              39.687500000000000000
              701.145833333333200000
              161.395833333333300000
              269.875000000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Color = clWhite
            DataSet = sp_brxx
            DataField = 'brxm'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 10
          end
          object QRLabel14: TQRLabel
            Left = 373
            Top = 61
            Width = 54
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              986.895833333333300000
              161.395833333333300000
              142.875000000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #24202#20301#21495':'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object QRDBText3: TQRDBText
            Left = 433
            Top = 61
            Width = 51
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              1145.645833333333000000
              161.395833333333300000
              134.937500000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = False
            AutoStretch = False
            Color = clWhite
            DataSet = sp_brxx
            DataField = 'bch'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = #23435#20307
            Font.Style = []
            ParentFont = False
            Transparent = False
            WordWrap = True
            FontSize = 10
          end
          object QRLabel16: TQRLabel
            Left = 501
            Top = 62
            Width = 39
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              1325.562500000000000000
              164.041666666666700000
              103.187500000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #30149#21306':'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object qrl_bqmc: TQRLabel
            Left = 573
            Top = 61
            Width = 39
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              1516.062500000000000000
              161.395833333333300000
              103.187500000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = #30149#21306':'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object rtl_czks: TQRLabel
            Left = 95
            Top = 41
            Width = 41
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              251.354166666666700000
              108.479166666666700000
              108.479166666666700000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = 'czks:'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
          object rtl_sfrq: TQRLabel
            Left = 306
            Top = 38
            Width = 33
            Height = 16
            Frame.Color = clBlack
            Frame.DrawTop = False
            Frame.DrawBottom = False
            Frame.DrawLeft = False
            Frame.DrawRight = False
            Size.Values = (
              42.333333333333330000
              809.625000000000000000
              100.541666666666700000
              87.312500000000000000)
            Alignment = taLeftJustify
            AlignToBand = False
            AutoSize = True
            AutoStretch = False
            Caption = 'sfrq'
            Color = clWhite
            Transparent = False
            WordWrap = True
            FontSize = 11
          end
        end
      end
    end
  end
  object Panel7: TPanel
    Left = 0
    Top = 0
    Width = 883
    Height = 57
    Align = alTop
    BevelInner = bvLowered
    TabOrder = 0
    object Label39: TLabel
      Left = 4
      Top = 8
      Width = 69
      Height = 15
      Caption = #20303' '#38498' '#21495':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label40: TLabel
      Left = 371
      Top = 8
      Width = 46
      Height = 15
      Caption = #24615' '#21035':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label41: TLabel
      Left = 456
      Top = 8
      Width = 46
      Height = 15
      Caption = #24180' '#40836':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label42: TLabel
      Left = 4
      Top = 31
      Width = 68
      Height = 15
      Caption = #20837#38498#26085#26399':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label43: TLabel
      Left = 190
      Top = 31
      Width = 68
      Height = 15
      Caption = #20837#38498#35786#26029':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label45: TLabel
      Left = 371
      Top = 31
      Width = 68
      Height = 15
      Caption = #39044#20132#37329#39069':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label46: TLabel
      Left = 552
      Top = 31
      Width = 68
      Height = 15
      Caption = #36153#29992#37329#39069':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label47: TLabel
      Left = 724
      Top = 31
      Width = 38
      Height = 15
      Caption = #31867#21035':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label48: TLabel
      Left = 552
      Top = 8
      Width = 68
      Height = 15
      Caption = #20027#31649#21307#29983':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label49: TLabel
      Left = 724
      Top = 8
      Width = 38
      Height = 15
      Caption = #22791#27880':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object Label50: TLabel
      Left = 190
      Top = 8
      Width = 68
      Height = 15
      Caption = #30149#20154#22995#21517':'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
    end
    object DBEdit9: TDBEdit
      Left = 73
      Top = 29
      Width = 110
      Height = 21
      TabStop = False
      Color = clCream
      Ctl3D = False
      DataField = 'ryrq'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 3
    end
    object DBEdit10: TDBEdit
      Left = 257
      Top = 29
      Width = 95
      Height = 21
      TabStop = False
      Color = clCream
      Ctl3D = False
      DataField = 'ryzd'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 4
    end
    object DBEdit11: TDBEdit
      Left = 619
      Top = 5
      Width = 88
      Height = 21
      TabStop = False
      Color = clCream
      Ctl3D = False
      DataField = 'zgys'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 5
    end
    object DBEdit12: TDBEdit
      Left = 440
      Top = 29
      Width = 91
      Height = 21
      TabStop = False
      Color = clMoneyGreen
      Ctl3D = False
      DataField = 'yjze'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 6
    end
    object DBEdit13: TDBEdit
      Left = 620
      Top = 29
      Width = 88
      Height = 21
      Color = clMoneyGreen
      Ctl3D = False
      DataField = 'zfy'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 7
    end
    object DBEdit14: TDBEdit
      Left = 257
      Top = 5
      Width = 95
      Height = 21
      TabStop = False
      Color = clCream
      Ctl3D = False
      DataField = 'brxm'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 2
    end
    object DBEdit15: TDBEdit
      Left = 504
      Top = 5
      Width = 28
      Height = 21
      TabStop = False
      Color = clCream
      Ctl3D = False
      DataField = 'brnl'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 1
    end
    object DBEdit16: TDBEdit
      Left = 419
      Top = 5
      Width = 23
      Height = 21
      TabStop = False
      Color = clCream
      Ctl3D = False
      DataField = 'brxb'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 0
    end
    object DBEdit17: TDBEdit
      Left = 764
      Top = 29
      Width = 104
      Height = 21
      Color = clMoneyGreen
      Ctl3D = False
      DataField = 'lbmc'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 8
    end
    object DBEdit18: TDBEdit
      Left = 764
      Top = 5
      Width = 104
      Height = 21
      TabStop = False
      Color = clCream
      Ctl3D = False
      DataField = 'bz'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 9
    end
    object DBEdit19: TDBEdit
      Left = 73
      Top = 4
      Width = 110
      Height = 21
      TabStop = False
      Color = clCream
      Ctl3D = False
      DataField = 'tmh'
      DataSource = ds_brxx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 10
    end
  end
  object qry_pub: TADOQuery
    Connection = DM_data.ado_mydata
    LockType = ltBatchOptimistic
    Parameters = <>
    Left = 544
    Top = 168
  end
  object ds_kdys: TDataSource
    DataSet = qry_kdys
    Left = 240
    Top = 216
  end
  object qry_kdys: TADOQuery
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    Parameters = <
      item
        Name = 'cxksdm'
        Attributes = [paNullable]
        DataType = ftString
        NumericScale = 255
        Precision = 255
        Size = 4
        Value = Null
      end>
    SQL.Strings = (
      
        'select dm,mc from sys_czy where ksdm=:cxksdm and sybz=1 and ysbz' +
        '=1 and cfbz=1')
    Left = 240
    Top = 168
  end
  object ds_xzzyyz: TDataSource
    DataSet = sp_xzzyyz
    Left = 280
    Top = 219
  end
  object ds_yzph: TDataSource
    Left = 320
    Top = 216
  end
  object ds_jbxx: TDataSource
    DataSet = sp_jbxx
    Left = 584
    Top = 168
  end
  object ds_brxx: TDataSource
    DataSet = sp_brxx
    OnDataChange = ds_brxxDataChange
    Left = 504
    Top = 168
  end
  object sp_xzzyyz: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    ProcedureName = 'zybl_yzcx_bcjfyz;1'
    Parameters = <
      item
        Name = '@zxbh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 10
        Value = #39#39
      end>
    Left = 288
    Top = 168
  end
  object sp_ysdm: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    ProcedureName = 'zybl_yzcx_bcjfyz;1'
    Parameters = <
      item
        Name = '@RETURN_VALUE'
        DataType = ftInteger
        Direction = pdReturnValue
        Precision = 10
        Value = 0
      end
      item
        Name = '@phlist'
        Attributes = [paNullable]
        DataType = ftString
        Size = 2000
        Value = #39#39
      end
      item
        Name = '@yzlb'
        Attributes = [paNullable]
        DataType = ftString
        Size = 10
        Value = #39#39
      end>
    Left = 392
    Top = 168
  end
  object ds_yf: TDataSource
    Left = 392
    Top = 216
  end
  object sp_yz_plzx: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    ProcedureName = 'zybl_yzup_plzx;1'
    Parameters = <
      item
        Name = '@ph'
        Attributes = [paNullable]
        DataType = ftString
        Size = 8000
        Value = Null
      end
      item
        Name = '@zxbh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 10
        Value = Null
      end
      item
        Name = '@pldh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 16
        Value = Null
      end
      item
        Name = '@zxsj'
        Attributes = [paNullable]
        DataType = ftString
        Size = 8
        Value = Null
      end
      item
        Name = '@qyyf'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = Null
      end>
    Left = 432
    Top = 168
  end
  object sp_sczbsj: TADOStoredProc
    Connection = DM_data.ado_mydata
    ProcedureName = 'zybl_yzup_sjzb_qcsj;1'
    Parameters = <
      item
        Name = '@zxbh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 10
        Value = Null
      end
      item
        Name = '@zyh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 16
        Value = Null
      end>
    Left = 360
    Top = 168
  end
  object sp_sjzb: TADOStoredProc
    Connection = DM_data.ado_mydata
    ProcedureName = 'zybl_yzup_bryz_pl_sjzb;1'
    Parameters = <
      item
        Name = '@zyh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 16
        Value = Null
      end
      item
        Name = '@czydm'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = Null
      end
      item
        Name = '@zxbh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 10
        Value = Null
      end
      item
        Name = '@yzselect'
        Attributes = [paNullable]
        DataType = ftString
        Size = 50
        Value = Null
      end>
    Left = 320
    Top = 168
  end
  object sp_clsjzb: TADOStoredProc
    Connection = DM_data.ado_mydata
    ProcedureName = 'zybl_yzup_bryzclmx_pl_sjzb;1'
    Parameters = <
      item
        Name = '@ph'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4000
        Value = Null
      end
      item
        Name = '@czydm'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = Null
      end
      item
        Name = '@cfks'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = Null
      end
      item
        Name = '@ksdm'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = Null
      end
      item
        Name = '@pldh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 16
        Value = Null
      end
      item
        Name = '@zxbh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 10
        Value = Null
      end>
    Left = 472
    Top = 168
  end
  object Ds_plzx: TDataSource
    DataSet = sp_yz_plzx
    OnDataChange = ds_brxxDataChange
    Left = 432
    Top = 216
  end
  object ad_plcl: TADODataSet
    Connection = DM_data.ado_mydata
    Parameters = <>
    Left = 356
    Top = 216
  end
  object sp_brxx: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    AfterScroll = sp_brxxAfterScroll
    ProcedureName = 'zybl_cx_zybrbq;1'
    Parameters = <
      item
        Name = '@sr_bqdm'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = ' '
      end>
    Left = 472
    Top = 216
  end
  object ds_fymx: TDataSource
    DataSet = qry_fymx
    Left = 512
    Top = 214
  end
  object qry_fymx: TADOQuery
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    Parameters = <
      item
        Name = 'zyh'
        DataType = ftString
        NumericScale = 255
        Precision = 255
        Size = 16
        Value = #8216#8217
      end>
    SQL.Strings = (
      
        'select fymx.id,fymx.tmh,fymx.zyh,fymx.fyje,czks.mc czks,kdks.mc ' +
        'kdks,'
      '       fymx.sfrq,czy.mc sfczy,fymx.sjbh,fymx.jsdh,'
      '       fymx.jsbz tfbz,fymx.tfrq,fymx.tfczy,zydj.brxm,'
      '       kdys.mc kdys,czys.mc czys,sfxm.fymc,sfxm.dw,'
      
        '       case when substring(fymx.bz,1,1)='#39'C'#39' then '#39#26159#39' else '#39#21542#39' en' +
        'd yjqrbz'
      
        '   from zysf_zyfymx fymx ,sys_czy czy,sys_czy kdys ,sys_czy czys' +
        ','
      
        '        sys_ksdm  czks, sys_ksdm kdks,zysf_zydj zydj,sys_kjsfxm ' +
        'sfxm'
      '   where fymx.sfczy=czy.dm   and'
      '         fymx.czks=czks.dm   and'
      '         fymx.kdks=kdks.dm   and'
      '         fymx.kdys*=kdys.dm  and'
      '         fymx.czys*=czys.dm  and'
      '         fymx.fydm=sfxm.fydm and'
      '         fymx.zyh=zydj.zyh      and'
      '         fymx.zyh = :zyh'
      '  order by sfrq desc')
    Left = 547
    Top = 214
  end
  object sp_jbxx: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    ProcedureName = 'zybl_cx_zybrdj;1'
    Parameters = <
      item
        Name = '@zyh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 16
        Value = Null
      end>
    Left = 584
    Top = 216
  end
  object qry_yjddy: TADOQuery
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    Parameters = <>
    SQL.Strings = (
      
        'select  fymc id, fymc ,  dw , sfbz fyje,  dymc sfrq  from sys_kj' +
        'sfxm where 1=2')
    Left = 675
    Top = 182
  end
end
