object frm_syfz: Tfrm_syfz
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  Caption = #30149#21306#36755#28082#20998#32452
  ClientHeight = 523
  ClientWidth = 772
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = #23435#20307
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poMainFormCenter
  Scaled = False
  OnCloseQuery = FormCloseQuery
  OnKeyPress = FormKeyPress
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 15
  object GroupBox1: TGroupBox
    Left = 0
    Top = 0
    Width = 772
    Height = 523
    Align = alClient
    TabOrder = 0
    object cxGroupBox1: TcxGroupBox
      Left = 2
      Top = 435
      Caption = #20998#32452#21450#29992#33647#35828#26126
      ParentFont = False
      Style.BorderStyle = ebsSingle
      Style.Font.Charset = ANSI_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -13
      Style.Font.Name = #23435#20307
      Style.Font.Style = []
      Style.IsFontAssigned = True
      TabOrder = 2
      Height = 112
      Width = 790
      object dbm_fzsm: TcxDBMemo
        Left = 3
        Top = 14
        DataBinding.DataField = 'fzsm'
        DataBinding.DataSource = ds_fzsm
        Properties.ReadOnly = True
        TabOrder = 0
        Height = 95
        Width = 784
      end
    end
    object GroupBox2: TGroupBox
      Left = 2
      Top = 17
      Width = 768
      Height = 43
      Align = alTop
      TabOrder = 0
      object Label1: TLabel
        Left = 168
        Top = 18
        Width = 68
        Height = 15
        Caption = #30149#21306#30149#21592':'
      end
      object Label2: TLabel
        Left = 352
        Top = 18
        Width = 38
        Height = 15
        Caption = #23646#24615':'
      end
      object Label3: TLabel
        Left = 12
        Top = 18
        Width = 38
        Height = 15
        Caption = #23646#24615':'
      end
      object Button1: TButton
        Left = 508
        Top = 12
        Width = 75
        Height = 25
        Caption = #26597#35810'(&S)'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        OnClick = Button1Click
      end
      object ComboBox1: TComboBox
        Left = 240
        Top = 14
        Width = 105
        Height = 23
        ItemHeight = 0
        TabOrder = 0
        OnChange = ComboBox1Change
      end
      object Button2: TButton
        Left = 582
        Top = 12
        Width = 75
        Height = 25
        Caption = #25171#21360'(&P)'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        OnClick = Button2Click
      end
      object Button3: TButton
        Left = 656
        Top = 12
        Width = 75
        Height = 25
        Caption = #36820#22238'(&B)'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        OnClick = Button3Click
      end
      object ComboBox2: TComboBox
        Left = 394
        Top = 14
        Width = 100
        Height = 23
        ItemHeight = 15
        TabOrder = 4
        OnChange = ComboBox1Change
        Items.Strings = (
          #38271#26399
          #20020#26102
          #22065#25176)
      end
      object DateTimePicker1: TDateTimePicker
        Left = 53
        Top = 14
        Width = 105
        Height = 23
        Date = 38773.626130821760000000
        Time = 38773.626130821760000000
        TabOrder = 5
      end
    end
    object cxGrid3: TcxGrid
      Left = 2
      Top = 60
      Width = 768
      Height = 461
      HelpType = htKeyword
      HelpKeyword = 'H'
      Align = alClient
      TabOrder = 1
      LookAndFeel.Kind = lfOffice11
      LookAndFeel.NativeStyle = False
      RootLevelOptions.DetailFrameWidth = 1
      object cxGridDBTableView3: TcxGridDBTableView
        NavigatorButtons.ConfirmDelete = False
        NavigatorButtons.First.Visible = True
        NavigatorButtons.PriorPage.Visible = True
        NavigatorButtons.Prior.Visible = True
        NavigatorButtons.Next.Visible = True
        NavigatorButtons.NextPage.Visible = True
        NavigatorButtons.Last.Visible = True
        NavigatorButtons.Insert.Visible = True
        NavigatorButtons.Delete.Visible = True
        NavigatorButtons.Edit.Visible = True
        NavigatorButtons.Post.Visible = True
        NavigatorButtons.Cancel.Visible = True
        NavigatorButtons.Refresh.Visible = True
        NavigatorButtons.SaveBookmark.Visible = True
        NavigatorButtons.GotoBookmark.Visible = True
        NavigatorButtons.Filter.Visible = True
        BackgroundBitmaps.Group.Data = {
          B62B0000424DB62B00000000000036000000280000004D000000300000000100
          180000000000802B0000D60E0000D60E00000000000000000000DDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCC
          CCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDD
          DDDDDDDDDDDDDDCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCC99BBBBBBCCCCCCCCCC99CCCCCCCCCC
          CC00DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCC
          CCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCC
          CCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBB
          BBBBCCCC99CCCCCCCCCC99CCCCCCBBBBBB00CCCCCCDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDD
          DDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBB
          BBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCC
          CCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCC00DDDDDDCCCCCC
          CCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          CCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCC99CCCC
          CC00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEE
          EEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBBBBBBBCCCC99
          BBBBBBCCCCCCBBBBBB00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEE
          EEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCCCCC99DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCBBBBBBBBBBBBCCCCCCBBBBBBCCCCCC00DDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCBBBBBBCCCCCCCCCC9900DDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEE
          DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEE
          EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCC
          CC00CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDD
          DDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCBBBBBB
          CCCCCCCCCCCCCCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBB
          BBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
          EEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCBBBBBBCCCCCCBBBBBBCCCC99CCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDCCCC
          CCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
          DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC99CCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCC00CCCCCCCCCCCC
          DDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEE
          DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCC
          CCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCC
          CC00CCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBB
          CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEE
          EEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDCCCCCCCCCCCCCCCCCC
          CCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBB
          BBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDD00CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
          CCCCBBBBBBCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDD
          DDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCC
          CCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDD
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEE
          EEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDD
          DDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCC
          CCCCCCDDDDDDCCCC99CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEE
          EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDD
          DDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCC99CCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDD
          DD00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCC
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEE
          EEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDD
          DDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDD
          DDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEE
          EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC
          99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDDCCCCCCDDDDDDDDDD
          DDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDEEEEEEEEEEEEEEEE
          EEDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDD
          DDCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCC
          CCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDD
          DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCDDDDDD
          CCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DD00DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBB
          BBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDD
          DDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCC
          CCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
          CCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD00DDDDDDCCCCCCDDDDDDCCCCCCCCCC
          CCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDD
          DDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDD00CCCCCCCCCCCC
          CCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDD
          DDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
          DD00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          DDDDDDDDDDDDCCCCCC00CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDD
          DDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
          DDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDD
          DDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCC00CCCCCCCCCCCCDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDCCCCCCDDDDDDCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDD
          DDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEE
          EEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCC00CCCCCCCCCCCC
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEE
          EEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCC
          CCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBB
          BBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CC00DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCC
          CCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
          DDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCC
          CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDCCCCCC00DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCDDDDDDDDDDDDEE
          EEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          CCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDD
          DDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEE
          EEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
          DDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCC
          CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CC00CCCCCCDDDDDDCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCC
          DDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDD
          DDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDD
          DDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCC
          CCCCCCCC99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCBBBBBB
          CCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBB
          BBBBBBBBBBCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDD
          DDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDD
          DDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDD
          DDCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCDDDD
          DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          BBBBBBCCCCCCBBBBBBCCCCCCBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CC00DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBBBB
          CCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEE
          EEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDD
          DDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE
          DDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCC
          DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDD
          DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
          EEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDEEEEEEEEEEEEDDDD
          DDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEE
          EEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDD
          CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDD
          DDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDD
          DDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEE
          EE00DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEE
          EEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDD
          DDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDEEEEEEDDDDDD00DDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDD
          DDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDD
          DDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDD
          DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEE
          EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDDEEEEEEDDDDDDEEEE
          EEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
          DDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEE
          EEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDD
          EEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDD
          DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDEEEEEEDDDD
          DDADDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDD
          DDEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEA4EEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEE
          EEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEE
          EEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEE
          EEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE16EEEEEEEEEEEEEEEEEEEEEEEEDDDD
          DDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDD
          DDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEE00}
        DataController.DataSource = ds_ypmx
        DataController.Summary.DefaultGroupSummaryItems = <>
        DataController.Summary.FooterSummaryItems = <>
        DataController.Summary.SummaryGroups = <
          item
            Links = <>
            SummaryItems = <>
          end>
        OptionsCustomize.ColumnFiltering = False
        OptionsCustomize.ColumnMoving = False
        OptionsCustomize.ColumnSorting = False
        OptionsData.CancelOnExit = False
        OptionsData.Deleting = False
        OptionsData.DeletingConfirmation = False
        OptionsData.Editing = False
        OptionsData.Inserting = False
        OptionsSelection.CellSelect = False
        OptionsSelection.MultiSelect = True
        OptionsView.GroupByBox = False
        object cxGridDBTableView3fzhm: TcxGridDBColumn
          Caption = #20998#32452#32534#21495
          DataBinding.FieldName = 'fzhm'
          Visible = False
          GroupIndex = 1
          HeaderAlignmentHorz = taCenter
          SortIndex = 0
          SortOrder = soAscending
          Width = 84
        end
        object cxGridDBTableView3ph: TcxGridDBColumn
          Caption = #25191#34892#25209#21495
          DataBinding.FieldName = 'ph'
          HeaderAlignmentHorz = taCenter
          Width = 134
        end
        object cxGridDBTableView3bch: TcxGridDBColumn
          Caption = #30149#24202#21495
          DataBinding.FieldName = 'bch'
          Visible = False
          HeaderAlignmentHorz = taCenter
          Width = 36
        end
        object cxGridDBTableView3zyh: TcxGridDBColumn
          Caption = #20303#38498#21495
          DataBinding.FieldName = 'zyh'
          Visible = False
          GroupIndex = 0
          HeaderAlignmentHorz = taCenter
          SortIndex = 1
          SortOrder = soAscending
          Width = 132
        end
        object cxGridDBTableView3brxm: TcxGridDBColumn
          Caption = #30149#20154#22995#21517
          DataBinding.FieldName = 'brxm'
          HeaderAlignmentHorz = taCenter
          Width = 65
        end
        object cxGridDBTableView3xmmc: TcxGridDBColumn
          Caption = #33647#21697#21517#31216
          DataBinding.FieldName = 'xmmc'
          HeaderAlignmentHorz = taCenter
          Width = 179
        end
        object cxGridDBTableView3id: TcxGridDBColumn
          DataBinding.FieldName = 'id'
          Visible = False
          HeaderAlignmentHorz = taCenter
          Width = 84
        end
        object cxGridDBTableView3ypgg: TcxGridDBColumn
          Caption = #33647#21697#35268#26684
          DataBinding.FieldName = 'ypgg'
          HeaderAlignmentHorz = taCenter
          Width = 96
        end
        object cxGridDBTableView3xmdm: TcxGridDBColumn
          DataBinding.FieldName = 'xmdm'
          Visible = False
          HeaderAlignmentHorz = taCenter
          Width = 116
        end
        object cxGridDBTableView3fzsl: TcxGridDBColumn
          Caption = #25968#37327
          DataBinding.FieldName = 'fzsl'
          HeaderAlignmentHorz = taCenter
          Width = 39
        end
        object cxGridDBTableView3dw: TcxGridDBColumn
          Caption = #21333#20301
          DataBinding.FieldName = 'dw'
          HeaderAlignmentHorz = taCenter
          Width = 37
        end
        object cxGridDBTableView3ypyf: TcxGridDBColumn
          Caption = #29992#27861
          DataBinding.FieldName = 'ypyf'
          HeaderAlignmentHorz = taCenter
          Width = 45
        end
        object cxGridDBTableView3ypyl: TcxGridDBColumn
          Caption = #29992#37327
          DataBinding.FieldName = 'ypyl'
          HeaderAlignmentHorz = taCenter
          Width = 42
        end
        object cxGridDBTableView3yldw: TcxGridDBColumn
          DataBinding.FieldName = 'yldw'
          HeaderAlignmentHorz = taCenter
          Width = 28
          IsCaptionAssigned = True
        end
        object cxGridDBTableView3yytj: TcxGridDBColumn
          Caption = #29992#33647#36884#24452
          DataBinding.FieldName = 'yytj'
          HeaderAlignmentHorz = taCenter
          Width = 74
        end
      end
      object cxGridLevel3: TcxGridLevel
        GridView = cxGridDBTableView3
        Options.DetailFrameWidth = 0
      end
    end
    object Memo1: TMemo
      Left = 27
      Top = 94
      Width = 697
      Height = 201
      Lines.Strings = (
        'Memo1')
      TabOrder = 3
      Visible = False
    end
  end
  object rep_dryphz: TQuickRep
    Left = 8
    Top = 275
    Width = 794
    Height = 1123
    Frame.Color = clBlack
    Frame.DrawTop = False
    Frame.DrawBottom = False
    Frame.DrawLeft = False
    Frame.DrawRight = False
    DataSet = sp_ypmx
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -15
    Font.Name = #23435#20307
    Font.Style = []
    Functions.Strings = (
      'PAGENUMBER'
      'COLUMNNUMBER'
      'REPORTTITLE')
    Functions.DATA = (
      '0'
      '0'
      #39#39)
    Options = [FirstPageHeader, LastPageFooter]
    Page.Columns = 1
    Page.Orientation = poPortrait
    Page.PaperSize = Default
    Page.Values = (
      0.000000000000000000
      2970.000000000000000000
      0.000000000000000000
      2100.000000000000000000
      100.000000000000000000
      100.000000000000000000
      0.000000000000000000)
    PrinterSettings.Copies = 1
    PrinterSettings.OutputBin = Auto
    PrinterSettings.Duplex = False
    PrinterSettings.FirstPage = 0
    PrinterSettings.LastPage = 0
    PrinterSettings.UseStandardprinter = False
    PrinterSettings.UseCustomBinCode = False
    PrinterSettings.CustomBinCode = 0
    PrinterSettings.ExtendedDuplex = 0
    PrinterSettings.UseCustomPaperCode = False
    PrinterSettings.CustomPaperCode = 0
    PrinterSettings.PrintMetaFile = False
    PrinterSettings.PrintQuality = 0
    PrinterSettings.Collate = 0
    PrinterSettings.ColorOption = 0
    PrintIfEmpty = True
    SnapToGrid = True
    Units = MM
    Zoom = 100
    PrevFormStyle = fsStayOnTop
    PreviewInitialState = wsMaximized
    PrevShowThumbs = False
    PrevShowSearch = False
    PrevInitialZoom = qrZoomToFit
    object DetailBand1: TQRBand
      Left = 38
      Top = 96
      Width = 718
      Height = 18
      Frame.Color = clBlack
      Frame.DrawTop = False
      Frame.DrawBottom = False
      Frame.DrawLeft = False
      Frame.DrawRight = False
      AlignToBottom = False
      Color = clWhite
      TransparentBand = False
      ForceNewColumn = False
      ForceNewPage = False
      Size.Values = (
        47.625000000000000000
        1899.708333333333000000)
      PreCaluculateBandHeight = False
      KeepOnOnePage = False
      BandType = rbDetail
      object QRDBText12: TQRDBText
        Left = 2
        Top = 2
        Width = 36
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          5.291666666666667000
          5.291666666666667000
          95.250000000000000000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'fzhm'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
      object QRDBText16: TQRDBText
        Left = 38
        Top = 2
        Width = 132
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333340000
          100.541666666666700000
          5.291666666666667000
          349.250000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'xmmc'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = True
        WordWrap = True
        FontSize = 9
      end
      object QRDBText21: TQRDBText
        Left = 170
        Top = 2
        Width = 60
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          449.791666666666700000
          5.291666666666667000
          158.750000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'ypgg'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
      object QRDBText22: TQRDBText
        Left = 230
        Top = 2
        Width = 25
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          608.541666666666800000
          5.291666666666667000
          66.145833333333340000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'yytj'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
      object QRDBText23: TQRDBText
        Left = 255
        Top = 2
        Width = 20
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          674.687500000000000000
          5.291666666666667000
          52.916666666666660000)
        Alignment = taRightJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'fzsl'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
      object QRDBText24: TQRDBText
        Left = 275
        Top = 2
        Width = 22
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          727.604166666666800000
          5.291666666666667000
          58.208333333333340000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'yldw'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
      object QRDBText25: TQRDBText
        Left = 365
        Top = 2
        Width = 38
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          965.729166666666800000
          5.291666666666667000
          100.541666666666700000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'fzhm1'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
      object QRDBText26: TQRDBText
        Left = 403
        Top = 2
        Width = 132
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333340000
          1066.270833333333000000
          5.291666666666667000
          349.250000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'xmmc1'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = True
        WordWrap = True
        FontSize = 9
      end
      object QRDBText27: TQRDBText
        Left = 535
        Top = 2
        Width = 60
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          1415.520833333333000000
          5.291666666666667000
          158.750000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'ypgg1'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
      object QRDBText34: TQRDBText
        Left = 595
        Top = 2
        Width = 26
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          1574.270833333333000000
          5.291666666666667000
          68.791666666666680000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'yytj1'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
      object QRDBText35: TQRDBText
        Left = 620
        Top = 2
        Width = 20
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          1640.416666666667000000
          5.291666666666667000
          52.916666666666660000)
        Alignment = taRightJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'fzsl1'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
      object QRDBText36: TQRDBText
        Left = 640
        Top = 2
        Width = 20
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          1693.333333333333000000
          5.291666666666667000
          52.916666666666660000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'yldw1'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 9
      end
    end
    object QRGroup2: TQRGroup
      Left = 38
      Top = 0
      Width = 718
      Height = 96
      Frame.Color = clBlack
      Frame.DrawTop = False
      Frame.DrawBottom = False
      Frame.DrawLeft = False
      Frame.DrawRight = False
      AlignToBottom = False
      BeforePrint = QRGroup2BeforePrint
      Color = clWhite
      TransparentBand = False
      ForceNewColumn = False
      ForceNewPage = False
      Size.Values = (
        254.000000000000000000
        1899.708333333333000000)
      PreCaluculateBandHeight = False
      KeepOnOnePage = False
      Expression = 'sp_ypmx.zyh'
      FooterBand = QRBand1
      Master = rep_dryphz
      ReprintOnNewPage = False
      object QRLabel22: TQRLabel
        Left = 11
        Top = 10
        Width = 326
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          29.104166666666670000
          26.458333333333330000
          862.541666666666900000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Caption = #21307#38498#36755#28082#21345
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clNavy
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 12
      end
      object QRLabel23: TQRLabel
        Left = 371
        Top = 10
        Width = 342
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          981.604166666666800000
          26.458333333333330000
          904.875000000000000000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Caption = #21307#38498#36755#28082#21345
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clNavy
        Font.Height = -16
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 12
      end
      object QRLabel24: TQRLabel
        Left = 37
        Top = 37
        Width = 34
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          97.895833333333330000
          97.895833333333330000
          89.958333333333330000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #22995#21517':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText28: TQRDBText
        Left = 77
        Top = 36
        Width = 54
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          203.729166666666700000
          95.250000000000000000
          142.875000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'brxm'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel30: TQRLabel
        Left = 139
        Top = 37
        Width = 34
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          367.770833333333300000
          97.895833333333330000
          89.958333333333330000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #24202#21495':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText29: TQRDBText
        Left = 176
        Top = 37
        Width = 39
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          465.666666666666800000
          97.895833333333340000
          103.187500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'bch'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel31: TQRLabel
        Left = 393
        Top = 93
        Width = 47
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1039.812500000000000000
          246.062500000000000000
          124.354166666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #20303#38498#21495':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText30: TQRDBText
        Left = 267
        Top = 36
        Width = 71
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          706.437500000000000000
          95.250000000000000000
          187.854166666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'tmh'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel32: TQRLabel
        Left = 397
        Top = 37
        Width = 34
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1050.395833333333000000
          97.895833333333330000
          89.958333333333330000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #22995#21517':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText31: TQRDBText
        Left = 437
        Top = 36
        Width = 54
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1156.229166666667000000
          95.250000000000000000
          142.875000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'brxm'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel33: TQRLabel
        Left = 499
        Top = 37
        Width = 34
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1320.270833333333000000
          97.895833333333330000
          89.958333333333330000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #24202#21495':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText32: TQRDBText
        Left = 536
        Top = 37
        Width = 39
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1418.166666666667000000
          97.895833333333340000
          103.187500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'bch'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel34: TQRLabel
        Left = 577
        Top = 37
        Width = 47
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1526.645833333333000000
          97.895833333333330000
          124.354166666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #20303#38498#21495':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText33: TQRDBText
        Left = 627
        Top = 36
        Width = 71
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1658.937500000000000000
          95.250000000000000000
          187.854166666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_ypmx
        DataField = 'tmh'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel35: TQRLabel
        Left = 36
        Top = 58
        Width = 34
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          95.250000000000000000
          153.458333333333300000
          89.958333333333330000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #30149#21306':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel36: TQRLabel
        Left = 77
        Top = 58
        Width = 62
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          203.729166666666700000
          153.458333333333300000
          164.041666666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Caption = #30149#21306':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel37: TQRLabel
        Left = 139
        Top = 58
        Width = 34
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          367.770833333333300000
          153.458333333333300000
          89.958333333333330000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #26085#26399':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel38: TQRLabel
        Left = 179
        Top = 58
        Width = 158
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          473.604166666666700000
          153.458333333333300000
          418.041666666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Caption = #20998#32452#21495':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel39: TQRLabel
        Left = 396
        Top = 58
        Width = 34
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1047.750000000000000000
          153.458333333333300000
          89.958333333333330000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #30149#21306':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel40: TQRLabel
        Left = 437
        Top = 58
        Width = 62
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1156.229166666667000000
          153.458333333333300000
          164.041666666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Caption = #30149#21306':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel41: TQRLabel
        Left = 499
        Top = 58
        Width = 34
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1320.270833333333000000
          153.458333333333300000
          89.958333333333330000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #26085#26399':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel42: TQRLabel
        Left = 539
        Top = 58
        Width = 158
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1426.104166666667000000
          153.458333333333300000
          418.041666666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Caption = #20998#32452#21495':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel43: TQRLabel
        Left = 9
        Top = 76
        Width = 29
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          23.812500000000000000
          201.083333333333300000
          76.729166666666670000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #32452#21495
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel44: TQRLabel
        Left = 63
        Top = 76
        Width = 74
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          166.687500000000000000
          201.083333333333300000
          195.791666666666700000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #33647' '#21697' '#21517' '#31216
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel45: TQRLabel
        Left = 173
        Top = 77
        Width = 53
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          457.729166666666700000
          203.729166666666700000
          140.229166666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #33647#21697#35268#26684
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel46: TQRLabel
        Left = 230
        Top = 77
        Width = 27
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          608.541666666666700000
          203.729166666666700000
          71.437500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #36884#24452
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel47: TQRLabel
        Left = 260
        Top = 77
        Width = 27
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          687.916666666666700000
          203.729166666666700000
          71.437500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #29992#37327
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel48: TQRLabel
        Left = 373
        Top = 77
        Width = 29
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          986.895833333333300000
          203.729166666666700000
          76.729166666666670000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #32452#21495
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel49: TQRLabel
        Left = 432
        Top = 77
        Width = 74
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1143.000000000000000000
          203.729166666666700000
          195.791666666666700000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #33647' '#21697' '#21517' '#31216
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel50: TQRLabel
        Left = 539
        Top = 77
        Width = 53
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1426.104166666667000000
          203.729166666666700000
          140.229166666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #33647#21697#35268#26684
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel51: TQRLabel
        Left = 594
        Top = 77
        Width = 27
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1571.625000000000000000
          203.729166666666700000
          71.437500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #36884#24452
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel52: TQRLabel
        Left = 622
        Top = 77
        Width = 27
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1645.708333333333000000
          203.729166666666700000
          71.437500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #29992#37327
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRShape1: TQRShape
        Left = 4
        Top = 93
        Width = 349
        Height = 4
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          10.583333333333330000
          10.583333333333330000
          246.062500000000000000
          923.395833333333400000)
        Shape = qrsHorLine
        VertAdjust = 0
      end
      object QRShape3: TQRShape
        Left = 367
        Top = 92
        Width = 348
        Height = 4
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          10.583333333333330000
          971.020833333333400000
          243.416666666666700000
          920.750000000000000000)
        Shape = qrsHorLine
        VertAdjust = 0
      end
      object QRLabel1: TQRLabel
        Left = 289
        Top = 77
        Width = 27
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          764.645833333333300000
          203.729166666666700000
          71.437500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #26102#38388
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel2: TQRLabel
        Left = 318
        Top = 77
        Width = 40
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          841.375000000000000000
          203.729166666666700000
          105.833333333333300000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #25191#34892#20154
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel3: TQRLabel
        Left = 651
        Top = 77
        Width = 27
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1722.437500000000000000
          203.729166666666700000
          71.437500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #26102#38388
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel4: TQRLabel
        Left = 679
        Top = 77
        Width = 40
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          1796.520833333333000000
          203.729166666666700000
          105.833333333333300000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #25191#34892#20154
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel5: TQRLabel
        Left = 217
        Top = 37
        Width = 47
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          574.145833333333300000
          97.895833333333330000
          124.354166666666700000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #20303#38498#21495':'
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
    end
    object QRBand1: TQRBand
      Left = 38
      Top = 114
      Width = 718
      Height = 32
      Frame.Color = clBlack
      Frame.DrawTop = False
      Frame.DrawBottom = False
      Frame.DrawLeft = False
      Frame.DrawRight = False
      AlignToBottom = False
      Color = clWhite
      TransparentBand = False
      ForceNewColumn = False
      ForceNewPage = False
      Size.Values = (
        84.666666666666670000
        1899.708333333333000000)
      PreCaluculateBandHeight = False
      KeepOnOnePage = False
      BandType = rbGroupFooter
      object QRShape9: TQRShape
        Left = 4
        Top = -1
        Width = 348
        Height = 4
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          10.583333333333330000
          10.583333333333330000
          -2.645833333333333000
          920.750000000000000000)
        Shape = qrsHorLine
        VertAdjust = 0
      end
      object QRRichText1: TQRRichText
        Left = 9
        Top = 5
        Width = 340
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          23.812500000000000000
          13.229166666666670000
          899.583333333333300000)
        Alignment = taLeftJustify
        AutoStretch = True
        Color = clWindow
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = #23435#20307
        Font.Style = []
      end
      object QRRichText2: TQRRichText
        Left = 373
        Top = 6
        Width = 340
        Height = 17
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          44.979166666666670000
          986.895833333333400000
          15.875000000000000000
          899.583333333333400000)
        Alignment = taLeftJustify
        AutoStretch = True
        Color = clWindow
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = #23435#20307
        Font.Style = []
      end
      object QRShape2: TQRShape
        Left = 368
        Top = -1
        Width = 348
        Height = 4
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          10.583333333333330000
          973.666666666666900000
          -2.645833333333333000
          920.750000000000000000)
        Shape = qrsHorLine
        VertAdjust = 0
      end
    end
  end
  object sp_ypmx: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    ProcedureName = 'zybl_yzcx_drypfz;1'
    Parameters = <
      item
        Name = '@RETURN_VALUE'
        DataType = ftInteger
        Direction = pdReturnValue
        Precision = 10
        Value = Null
      end
      item
        Name = '@zyh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 16
        Value = #39#39
      end
      item
        Name = '@yzsx'
        Attributes = [paNullable]
        DataType = ftString
        Size = 10
        Value = #39#39
      end
      item
        Name = '@yzsj'
        Attributes = [paNullable]
        DataType = ftDateTime
        Value = 38750d
      end>
    Left = 80
    Top = 136
  end
  object ds_ypmx: TDataSource
    DataSet = sp_ypmx
    OnDataChange = ds_ypmxDataChange
    Left = 120
    Top = 136
  end
  object sp_brxx: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    ProcedureName = 'zybl_cx_zybrbq;1'
    Parameters = <
      item
        Name = '@RETURN_VALUE'
        DataType = ftInteger
        Direction = pdReturnValue
        Precision = 10
        Value = Null
      end
      item
        Name = '@sr_bqdm'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = #39#39
      end>
    Left = 40
    Top = 88
  end
  object ds_brxx: TDataSource
    DataSet = sp_brxx
    Left = 72
    Top = 88
  end
  object qry_fzsm: TADOQuery
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    Parameters = <>
    SQL.Strings = (
      'select * from zybl_zyyz_syfzsm')
    Left = 240
    Top = 328
  end
  object ds_fzsm: TDataSource
    DataSet = qry_fzsm
    Left = 200
    Top = 328
  end
  object qry_pub: TADOQuery
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    Parameters = <>
    SQL.Strings = (
      'select * from zybl_zyyz_syfzsm')
    Left = 304
    Top = 328
  end
end
