object frm_yjddy: Tfrm_yjddy
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  Caption = #21307#25216#21333#25171#21360
  ClientHeight = 573
  ClientWidth = 792
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = #23435#20307
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  Scaled = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 15
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 792
    Height = 49
    Align = alTop
    BevelInner = bvLowered
    TabOrder = 0
    object Label1: TLabel
      Left = 10
      Top = 20
      Width = 38
      Height = 15
      Caption = #30149#21592':'
    end
    object Label3: TLabel
      Left = 172
      Top = 20
      Width = 38
      Height = 15
      Caption = #26085#26399':'
    end
    object Label4: TLabel
      Left = 343
      Top = 20
      Width = 15
      Height = 15
      Caption = #33267
    end
    object ksrq: TcxDateEdit
      Left = 212
      Top = 12
      TabOrder = 0
      OnKeyDown = ksrqKeyDown
      Width = 121
    end
    object jzrq: TcxDateEdit
      Left = 374
      Top = 12
      TabOrder = 1
      OnKeyDown = jzrqKeyDown
      Width = 121
    end
    object cxButton1: TcxButton
      Left = 506
      Top = 13
      Width = 75
      Height = 22
      Caption = #26597#35810'(&S)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnClick = cxButton1Click
    end
    object cxButton3: TcxButton
      Left = 587
      Top = 13
      Width = 99
      Height = 22
      Caption = #21307#25216#30830#35748#21333'(&Y)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnClick = cxButton3Click
    end
    object cxButton4: TcxButton
      Left = 701
      Top = 13
      Width = 75
      Height = 22
      Caption = #36820#22238'(&B)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      OnClick = cxButton4Click
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 81
    Width = 792
    Height = 492
    Align = alClient
    BevelInner = bvLowered
    TabOrder = 1
    object cxGrid3: TcxGrid
      Left = 2
      Top = 2
      Width = 788
      Height = 488
      HelpType = htKeyword
      HelpKeyword = 'H'
      Align = alClient
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      LookAndFeel.Kind = lfOffice11
      LookAndFeel.NativeStyle = False
      RootLevelOptions.DetailFrameWidth = 1
      object cxGridDBTableView3: TcxGridDBTableView
        NavigatorButtons.ConfirmDelete = False
        NavigatorButtons.First.Visible = True
        NavigatorButtons.PriorPage.Visible = True
        NavigatorButtons.Prior.Visible = True
        NavigatorButtons.Next.Visible = True
        NavigatorButtons.NextPage.Visible = True
        NavigatorButtons.Last.Visible = True
        NavigatorButtons.Insert.Visible = True
        NavigatorButtons.Delete.Visible = True
        NavigatorButtons.Edit.Visible = True
        NavigatorButtons.Post.Visible = True
        NavigatorButtons.Cancel.Visible = True
        NavigatorButtons.Refresh.Visible = True
        NavigatorButtons.SaveBookmark.Visible = True
        NavigatorButtons.GotoBookmark.Visible = True
        NavigatorButtons.Filter.Visible = True
        OnCellClick = cxGridDBTableView3CellClick
        BackgroundBitmaps.Group.Data = {
          B62B0000424DB62B00000000000036000000280000004D000000300000000100
          180000000000802B0000D60E0000D60E00000000000000000000DDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCC
          CCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDD
          DDDDDDDDDDDDDDCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCC99BBBBBBCCCCCCCCCC99CCCCCCCCCC
          CC00DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCC
          CCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCC
          CCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBB
          BBBBCCCC99CCCCCCCCCC99CCCCCCBBBBBB00CCCCCCDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDD
          DDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBB
          BBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCC
          CCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCC00DDDDDDCCCCCC
          CCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          CCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCC99CCCC
          CC00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEE
          EEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBBBBBBBCCCC99
          BBBBBBCCCCCCBBBBBB00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEE
          EEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCCCCC99DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCBBBBBBBBBBBBCCCCCCBBBBBBCCCCCC00DDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCBBBBBBCCCCCCCCCC9900DDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEE
          DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEE
          EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCC
          CC00CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDD
          DDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCBBBBBB
          CCCCCCCCCCCCCCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBB
          BBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
          EEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCBBBBBBCCCCCCBBBBBBCCCC99CCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDCCCC
          CCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
          DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC99CCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCC00CCCCCCCCCCCC
          DDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEE
          DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCC
          CCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCC
          CC00CCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBB
          CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEE
          EEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDCCCCCCCCCCCCCCCCCC
          CCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBB
          BBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDD00CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
          CCCCBBBBBBCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDD
          DDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCC
          CCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDD
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEE
          EEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDD
          DDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCC
          CCCCCCDDDDDDCCCC99CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEE
          EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDD
          DDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCC99CCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDD
          DD00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCC
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEE
          EEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDD
          DDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDD
          DDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEE
          EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC
          99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDDCCCCCCDDDDDDDDDD
          DDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDEEEEEEEEEEEEEEEE
          EEDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDD
          DDCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCC
          CCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDD
          DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCDDDDDD
          CCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DD00DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBB
          BBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDD
          DDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCC
          CCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
          CCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD00DDDDDDCCCCCCDDDDDDCCCCCCCCCC
          CCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDD
          DDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDD00CCCCCCCCCCCC
          CCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDD
          DDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
          DD00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          DDDDDDDDDDDDCCCCCC00CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDD
          DDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
          DDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDD
          DDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCC00CCCCCCCCCCCCDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDCCCCCCDDDDDDCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDD
          DDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEE
          EEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCC00CCCCCCCCCCCC
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEE
          EEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCC
          CCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBB
          BBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CC00DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCC
          CCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
          DDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCC
          CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDCCCCCC00DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCDDDDDDDDDDDDEE
          EEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          CCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDD
          DDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEE
          EEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
          DDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCC
          CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CC00CCCCCCDDDDDDCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCC
          DDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDD
          DDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDD
          DDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCC
          CCCCCCCC99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCBBBBBB
          CCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBB
          BBBBBBBBBBCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDD
          DDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDD
          DDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDD
          DDCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCDDDD
          DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          BBBBBBCCCCCCBBBBBBCCCCCCBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CC00DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBBBB
          CCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEE
          EEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDD
          DDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE
          DDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCC
          DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDD
          DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
          EEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDEEEEEEEEEEEEDDDD
          DDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEE
          EEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDD
          CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDD
          DDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDD
          DDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEE
          EE00DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEE
          EEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDD
          DDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDEEEEEEDDDDDD00DDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDD
          DDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDD
          DDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDD
          DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEE
          EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDDEEEEEEDDDDDDEEEE
          EEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
          DDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEE
          EEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDD
          EEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDD
          DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDEEEEEEDDDD
          DDADDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDD
          DDEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEA4EEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEE
          EEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEE
          EEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEE
          EEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE16EEEEEEEEEEEEEEEEEEEEEEEEDDDD
          DDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDD
          DDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEE00}
        DataController.DataSource = ds_ypmx
        DataController.Summary.DefaultGroupSummaryItems = <>
        DataController.Summary.FooterSummaryItems = <>
        DataController.Summary.SummaryGroups = <
          item
            Links = <>
            SummaryItems = <>
          end>
        OptionsCustomize.ColumnFiltering = False
        OptionsCustomize.ColumnMoving = False
        OptionsData.CancelOnExit = False
        OptionsData.Deleting = False
        OptionsData.DeletingConfirmation = False
        OptionsData.Editing = False
        OptionsData.Inserting = False
        OptionsSelection.CellSelect = False
        OptionsSelection.MultiSelect = True
        OptionsView.GroupByBox = False
        object cxGridDBTableView3Column5: TcxGridDBColumn
          Caption = #36873#25321
          DataBinding.FieldName = 'xzbz'
          HeaderAlignmentHorz = taCenter
          Width = 30
        end
        object cxGridDBTableView3Column1: TcxGridDBColumn
          Caption = #22995#21517
          DataBinding.FieldName = 'brxm'
          HeaderAlignmentHorz = taCenter
          Width = 80
        end
        object cxGridDBTableView3Column2: TcxGridDBColumn
          Caption = #22788#32622#31185#23460
          DataBinding.FieldName = 'czks'
          HeaderAlignmentHorz = taCenter
          Width = 100
        end
        object cxGridDBTableView3Column3: TcxGridDBColumn
          Caption = #25910#36153#26085#26399
          DataBinding.FieldName = 'sfrq'
          HeaderAlignmentHorz = taCenter
          Width = 110
        end
        object cxGridDBTableView3zyh: TcxGridDBColumn
          DataBinding.FieldName = 'zyh'
          Visible = False
          HeaderAlignmentHorz = taCenter
          Width = 132
        end
        object cxGridDBTableView3brxm: TcxGridDBColumn
          Caption = #30149#24202#21495
          DataBinding.FieldName = 'brxm'
          Visible = False
          GroupIndex = 0
          HeaderAlignmentHorz = taCenter
          SortIndex = 0
          SortOrder = soAscending
          Width = 228
        end
        object cxGridDBTableView3id: TcxGridDBColumn
          DataBinding.FieldName = 'id'
          Visible = False
          HeaderAlignmentHorz = taCenter
          Width = 84
          IsCaptionAssigned = True
        end
        object cxGridDBTableView3xmdm: TcxGridDBColumn
          Caption = #39033#30446#32534#30721
          DataBinding.FieldName = 'fydm'
          HeaderAlignmentHorz = taCenter
          Width = 80
        end
        object cxGridDBTableView3xmmc: TcxGridDBColumn
          Caption = #39033#30446#21517#31216
          DataBinding.FieldName = 'fymc'
          HeaderAlignmentHorz = taCenter
          Width = 230
        end
        object cxGridDBTableView3sl: TcxGridDBColumn
          Caption = #25968#37327
          DataBinding.FieldName = 'sl'
          HeaderAlignmentHorz = taCenter
          Width = 43
        end
        object cxGridDBTableView3Column4: TcxGridDBColumn
          Caption = #37329#39069
          DataBinding.FieldName = 'fyje'
        end
      end
      object cxGridLevel3: TcxGridLevel
        GridView = cxGridDBTableView3
        Options.DetailFrameWidth = 0
      end
    end
  end
  object db_brxx: TDBGridEh
    Left = 44
    Top = 91
    Width = 176
    Height = 129
    DataSource = ds_jbxx
    Flat = True
    FooterColor = clWindow
    FooterFont.Charset = ANSI_CHARSET
    FooterFont.Color = clWindowText
    FooterFont.Height = -15
    FooterFont.Name = #23435#20307
    FooterFont.Style = []
    Options = [dgTitles, dgIndicator, dgColumnResize, dgColLines, dgRowLines, dgTabs, dgRowSelect, dgConfirmDelete, dgCancelOnExit]
    ReadOnly = True
    TabOrder = 2
    TitleFont.Charset = ANSI_CHARSET
    TitleFont.Color = clWindowText
    TitleFont.Height = -15
    TitleFont.Name = #23435#20307
    TitleFont.Style = []
    Visible = False
    OnDblClick = db_brxxDblClick
    OnExit = db_brxxExit
    OnKeyDown = db_brxxKeyDown
    Columns = <
      item
        EditButtons = <>
        FieldName = 'bch'
        Footers = <>
        Title.Alignment = taCenter
        Title.Caption = #24202#21495
        Width = 45
      end
      item
        EditButtons = <>
        FieldName = 'brxm'
        Footers = <>
        Title.Alignment = taCenter
        Title.Caption = #22995#21517
        Width = 80
      end>
  end
  object e_tmh: TEdit
    Left = 51
    Top = 13
    Width = 115
    Height = 21
    Color = clCaptionText
    Ctl3D = False
    ParentCtl3D = False
    TabOrder = 3
    OnExit = e_tmhExit
    OnKeyDown = e_tmhKeyDown
  end
  object Panel3: TPanel
    Left = 0
    Top = 49
    Width = 792
    Height = 32
    Align = alTop
    BevelInner = bvLowered
    TabOrder = 4
    object cxButton2: TcxButton
      Left = 17
      Top = 6
      Width = 75
      Height = 22
      Caption = #20840#36873'(&A)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      OnClick = cxButton2Click
    end
    object cxButton5: TcxButton
      Left = 98
      Top = 6
      Width = 68
      Height = 22
      Caption = #20840#19981#36873'(&N)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnClick = cxButton5Click
    end
    object cxButton6: TcxButton
      Left = 182
      Top = 6
      Width = 83
      Height = 22
      Caption = #38750#26412#31185#23460#36153#29992
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnClick = cxButton6Click
    end
  end
  object QuickRep1: TQuickRep
    Left = 0
    Top = 113
    Width = 816
    Height = 305
    Frame.Color = clBlack
    Frame.DrawTop = False
    Frame.DrawBottom = False
    Frame.DrawLeft = False
    Frame.DrawRight = False
    DataSet = sp_yjqrd
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -15
    Font.Name = #23435#20307
    Font.Style = []
    Functions.Strings = (
      'PAGENUMBER'
      'COLUMNNUMBER'
      'REPORTTITLE')
    Functions.DATA = (
      '0'
      '0'
      #39#39)
    Options = [FirstPageHeader, LastPageFooter]
    Page.Columns = 1
    Page.Orientation = poPortrait
    Page.PaperSize = Custom
    Page.Values = (
      100.000000000000000000
      808.000000000000000000
      100.000000000000000000
      2159.000000000000000000
      100.000000000000000000
      100.000000000000000000
      0.000000000000000000)
    PrinterSettings.Copies = 1
    PrinterSettings.OutputBin = Auto
    PrinterSettings.Duplex = False
    PrinterSettings.FirstPage = 0
    PrinterSettings.LastPage = 0
    PrinterSettings.UseStandardprinter = False
    PrinterSettings.UseCustomBinCode = False
    PrinterSettings.CustomBinCode = 0
    PrinterSettings.ExtendedDuplex = 0
    PrinterSettings.UseCustomPaperCode = False
    PrinterSettings.CustomPaperCode = 0
    PrinterSettings.PrintMetaFile = False
    PrinterSettings.PrintQuality = 0
    PrinterSettings.Collate = 0
    PrinterSettings.ColorOption = 0
    PrintIfEmpty = True
    SnapToGrid = True
    Units = MM
    Zoom = 100
    PrevFormStyle = fsStayOnTop
    PreviewInitialState = wsMaximized
    PrevShowThumbs = False
    PrevShowSearch = False
    PrevInitialZoom = qrZoomToFit
    object QRBand2: TQRBand
      Left = 38
      Top = 158
      Width = 740
      Height = 17
      Frame.Color = clBlack
      Frame.DrawTop = False
      Frame.DrawBottom = False
      Frame.DrawLeft = False
      Frame.DrawRight = False
      AlignToBottom = False
      Color = clWhite
      TransparentBand = False
      ForceNewColumn = False
      ForceNewPage = False
      Size.Values = (
        44.979166666666670000
        1957.916666666667000000)
      PreCaluculateBandHeight = False
      KeepOnOnePage = False
      BandType = rbDetail
      object QRDBText2: TQRDBText
        Left = 36
        Top = 1
        Width = 275
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          95.250000000000000000
          2.645833333333333000
          727.604166666666800000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_yjqrd
        DataField = 'fymc'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText10: TQRDBText
        Left = 430
        Top = 0
        Width = 51
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          1137.708333333333000000
          0.000000000000000000
          134.937500000000000000)
        Alignment = taRightJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_yjqrd
        DataField = 'sl'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText11: TQRDBText
        Left = 520
        Top = 1
        Width = 85
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          1375.833333333333000000
          2.645833333333333000
          224.895833333333300000)
        Alignment = taRightJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_yjqrd
        DataField = 'fyje'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        Mask = '#0.00'
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText15: TQRDBText
        Left = 313
        Top = 1
        Width = 85
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          828.145833333333200000
          2.645833333333333000
          224.895833333333300000)
        Alignment = taRightJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_yjqrd
        DataField = 'dj'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        Mask = '#0.00'
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRShape11: TQRShape
        Left = 2
        Top = -1
        Width = 2
        Height = 20
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          52.916666666666660000
          5.291666666666667000
          -2.645833333333333000
          5.291666666666667000)
        Shape = qrsVertLine
        VertAdjust = 0
      end
      object QRShape16: TQRShape
        Left = 714
        Top = -48
        Width = 2
        Height = 18
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          47.625000000000000000
          1889.125000000000000000
          -127.000000000000000000
          5.291666666666667000)
        Shape = qrsVertLine
        VertAdjust = 0
      end
      object QRShape17: TQRShape
        Left = 714
        Top = -48
        Width = 2
        Height = 18
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          47.625000000000000000
          1889.125000000000000000
          -127.000000000000000000
          5.291666666666667000)
        Shape = qrsVertLine
        VertAdjust = 0
      end
      object QRShape18: TQRShape
        Left = 714
        Top = -1
        Width = 2
        Height = 20
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          52.916666666666660000
          1889.125000000000000000
          -2.645833333333333000
          5.291666666666667000)
        Shape = qrsVertLine
        VertAdjust = 0
      end
    end
    object QRGroup1: TQRGroup
      Left = 38
      Top = 38
      Width = 740
      Height = 120
      Frame.Color = clBlack
      Frame.DrawTop = False
      Frame.DrawBottom = False
      Frame.DrawLeft = False
      Frame.DrawRight = False
      AlignToBottom = False
      Color = clWhite
      TransparentBand = False
      ForceNewColumn = False
      ForceNewPage = False
      Size.Values = (
        317.500000000000000000
        1957.916666666667000000)
      PreCaluculateBandHeight = False
      KeepOnOnePage = False
      Expression = 'sp_yjqrd.fzzd'
      FooterBand = QRBand4
      Master = QuickRep1
      ReprintOnNewPage = False
      object QRShape8: TQRShape
        Left = 4
        Top = 15
        Width = 712
        Height = 4
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          10.583333333333330000
          10.583333333333330000
          39.687500000000000000
          1883.833333333333000000)
        Shape = qrsHorLine
        VertAdjust = 0
      end
      object QRLabel22: TQRLabel
        Left = 8
        Top = 23
        Width = 683
        Height = 22
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          58.208333333333340000
          21.166666666666670000
          60.854166666666680000
          1807.104166666667000000)
        Alignment = taCenter
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Caption = #21307#25216#30830#35748#21333
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clNavy
        Font.Height = -21
        Font.Name = #23435#20307
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 16
      end
      object QRLabel13: TQRLabel
        Left = 35
        Top = 52
        Width = 54
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          92.604166666666670000
          137.583333333333300000
          142.875000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #20303#38498#21495':'
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRLabel14: TQRLabel
        Left = 200
        Top = 52
        Width = 54
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          529.166666666666700000
          137.583333333333300000
          142.875000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #24202#20301#21495':'
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRLabel16: TQRLabel
        Left = 499
        Top = 52
        Width = 39
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          1320.270833333333000000
          137.583333333333300000
          103.187500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #30149#21306':'
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRLabel17: TQRLabel
        Left = 35
        Top = 78
        Width = 69
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          92.604166666666670000
          206.375000000000000000
          182.562500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #32564#36153#26085#26399':'
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRLabel18: TQRLabel
        Left = 258
        Top = 78
        Width = 39
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          682.625000000000000000
          206.375000000000000000
          103.187500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #31185#23460':'
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRLabel19: TQRLabel
        Left = 35
        Top = 103
        Width = 61
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          92.604166666666670000
          272.520833333333300000
          161.395833333333300000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #30003#35831#39033#30446
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRLabel20: TQRLabel
        Left = 362
        Top = 103
        Width = 31
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          957.791666666666700000
          272.520833333333300000
          82.020833333333330000)
        Alignment = taRightJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #21333#20215
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRLabel21: TQRLabel
        Left = 450
        Top = 103
        Width = 31
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          1190.625000000000000000
          272.520833333333300000
          82.020833333333330000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #25968#37327
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRLabel23: TQRLabel
        Left = 558
        Top = 103
        Width = 46
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          1476.375000000000000000
          272.520833333333300000
          121.708333333333300000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #24635#37329#39069
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRShape9: TQRShape
        Left = 2
        Top = 17
        Width = 2
        Height = 105
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          277.812500000000000000
          5.291666666666667000
          44.979166666666670000
          5.291666666666667000)
        Shape = qrsVertLine
        VertAdjust = 0
      end
      object QRShape10: TQRShape
        Left = 714
        Top = 17
        Width = 2
        Height = 105
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          277.812500000000000000
          1889.125000000000000000
          44.979166666666670000
          5.291666666666667000)
        Shape = qrsVertLine
        VertAdjust = 0
      end
      object QRDBText13: TQRDBText
        Left = 258
        Top = 53
        Width = 235
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          682.625000000000000000
          140.229166666666700000
          621.770833333333400000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_yjqrd
        DataField = 'brxm'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText17: TQRDBText
        Left = 108
        Top = 79
        Width = 144
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          285.750000000000000000
          209.020833333333300000
          381.000000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_yjqrd
        DataField = 'sfrq'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRLabel25: TQRLabel
        Left = 544
        Top = 51
        Width = 39
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          1439.333333333333000000
          134.937500000000000000
          103.187500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #30149#21306':'
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRShape19: TQRShape
        Left = 4
        Top = 117
        Width = 711
        Height = 4
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          10.583333333333330000
          10.583333333333330000
          309.562500000000000000
          1881.187500000000000000)
        Shape = qrsHorLine
        VertAdjust = 0
      end
      object QRDBText12: TQRDBText
        Left = 95
        Top = 53
        Width = 100
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          251.354166666666700000
          140.229166666666700000
          264.583333333333400000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_yjqrd
        DataField = 'tmh'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
      object QRDBText18: TQRDBText
        Left = 317
        Top = 79
        Width = 164
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          838.729166666666800000
          209.020833333333300000
          433.916666666666800000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_yjqrd
        DataField = 'czks'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
    end
    object QRBand4: TQRBand
      Left = 38
      Top = 175
      Width = 740
      Height = 43
      Frame.Color = clBlack
      Frame.DrawTop = False
      Frame.DrawBottom = False
      Frame.DrawLeft = False
      Frame.DrawRight = False
      AlignToBottom = False
      Color = clWhite
      TransparentBand = False
      ForceNewColumn = False
      ForceNewPage = False
      Size.Values = (
        113.770833333333300000
        1957.916666666667000000)
      PreCaluculateBandHeight = False
      KeepOnOnePage = False
      BandType = rbGroupFooter
      object QRShape12: TQRShape
        Left = 3
        Top = 23
        Width = 713
        Height = 3
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          7.937500000000000000
          7.937500000000000000
          60.854166666666680000
          1886.479166666667000000)
        Shape = qrsHorLine
        VertAdjust = 0
      end
      object QRShape7: TQRShape
        Left = 4
        Top = -1
        Width = 711
        Height = 4
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          10.583333333333330000
          10.583333333333330000
          -2.645833333333333000
          1881.187500000000000000)
        Shape = qrsHorLine
        VertAdjust = 0
      end
      object QRShape13: TQRShape
        Left = 2
        Top = -53
        Width = 2
        Height = 18
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          47.625000000000000000
          5.291666666666667000
          -140.229166666666700000
          5.291666666666667000)
        Shape = qrsVertLine
        VertAdjust = 0
      end
      object QRShape14: TQRShape
        Left = 2
        Top = 0
        Width = 2
        Height = 25
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          66.145833333333340000
          5.291666666666667000
          0.000000000000000000
          5.291666666666667000)
        Shape = qrsVertLine
        VertAdjust = 0
      end
      object QRShape15: TQRShape
        Left = 714
        Top = 0
        Width = 2
        Height = 24
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          63.500000000000000000
          1889.125000000000000000
          0.000000000000000000
          5.291666666666667000)
        Shape = qrsVertLine
        VertAdjust = 0
      end
      object QRLabel24: TQRLabel
        Left = 516
        Top = 6
        Width = 54
        Height = 16
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          42.333333333333330000
          1365.250000000000000000
          15.875000000000000000
          142.875000000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = True
        AutoStretch = False
        Caption = #25805#20316#21592':'
        Color = clWhite
        Transparent = False
        WordWrap = True
        FontSize = 11
      end
      object QRDBText14: TQRDBText
        Left = 576
        Top = 6
        Width = 123
        Height = 15
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        Size.Values = (
          39.687500000000000000
          1524.000000000000000000
          15.875000000000000000
          325.437500000000000000)
        Alignment = taLeftJustify
        AlignToBand = False
        AutoSize = False
        AutoStretch = False
        Color = clWhite
        DataSet = sp_yjqrd
        DataField = 'sfczy'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        Transparent = False
        WordWrap = True
        FontSize = 10
      end
    end
  end
  object sp_yjqrd: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    AfterOpen = sp_yjqrdAfterOpen
    ProcedureName = 'zybl_yzcx_yjd'
    Parameters = <
      item
        Name = '@bqdm'
        DataType = ftString
        Size = 1
        Value = ' '
      end
      item
        Name = '@zyh'
        DataType = ftString
        Size = 1
        Value = ' '
      end
      item
        Name = '@ksrq'
        DataType = ftString
        Size = 1
        Value = ' '
      end
      item
        Name = '@jzrq'
        DataType = ftString
        Size = 1
        Value = ' '
      end>
    Left = 192
    Top = 182
  end
  object ds_ypmx: TDataSource
    DataSet = sp_yjqrd
    Left = 264
    Top = 182
  end
  object sp_jbxx: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    ProcedureName = 'bqgl_cx_zybrjbqk;1'
    Parameters = <
      item
        Name = '@tmh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 9
        Value = Null
      end
      item
        Name = '@xm'
        Attributes = [paNullable]
        DataType = ftString
        Size = 10
        Value = Null
      end
      item
        Name = '@bch'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = Null
      end
      item
        Name = '@ksdm'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = Null
      end>
    Left = 72
    Top = 184
  end
  object ds_jbxx: TDataSource
    DataSet = sp_jbxx
    Left = 128
    Top = 192
  end
end
