object frm_yzzxd: Tfrm_yzzxd
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  Caption = #30149#21306#21307#22065#25191#34892#21333
  ClientHeight = 523
  ClientWidth = 772
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = #23435#20307
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poMainFormCenter
  Scaled = False
  OnCloseQuery = FormCloseQuery
  OnKeyPress = FormKeyPress
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 15
  object GroupBox1: TGroupBox
    Left = 0
    Top = 0
    Width = 772
    Height = 523
    Align = alClient
    TabOrder = 0
    object GroupBox2: TGroupBox
      Left = 6
      Top = 7
      Width = 784
      Height = 43
      TabOrder = 0
      object Label1: TLabel
        Left = 16
        Top = 16
        Width = 68
        Height = 15
        Caption = #30149#21306#30149#21592':'
      end
      object Label2: TLabel
        Left = 240
        Top = 16
        Width = 68
        Height = 15
        Caption = #21307#22065#23646#24615':'
      end
      object Button1: TButton
        Left = 467
        Top = 12
        Width = 75
        Height = 25
        Caption = #26597#35810'(&S)'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        OnClick = Button1Click
      end
      object ComboBox1: TComboBox
        Left = 88
        Top = 12
        Width = 121
        Height = 23
        ItemHeight = 0
        TabOrder = 0
        OnChange = ComboBox1Change
      end
      object Button2: TButton
        Left = 541
        Top = 12
        Width = 75
        Height = 25
        Caption = #25171#21360'(&P)'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        OnClick = Button2Click
      end
      object Button3: TButton
        Left = 615
        Top = 12
        Width = 75
        Height = 25
        Caption = #36820#22238'(&B)'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = #23435#20307
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        OnClick = Button3Click
      end
      object ComboBox2: TComboBox
        Left = 320
        Top = 12
        Width = 121
        Height = 23
        ItemHeight = 15
        TabOrder = 4
        OnChange = ComboBox1Change
        Items.Strings = (
          #38271#26399
          #20020#26102
          #22065#25176)
      end
    end
    object cxGrid3: TcxGrid
      Left = 2
      Top = 52
      Width = 791
      Height = 495
      HelpType = htKeyword
      HelpKeyword = 'H'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      LookAndFeel.Kind = lfOffice11
      LookAndFeel.NativeStyle = False
      RootLevelOptions.DetailFrameWidth = 1
      object cxGridDBTableView3: TcxGridDBTableView
        NavigatorButtons.ConfirmDelete = False
        NavigatorButtons.First.Visible = True
        NavigatorButtons.PriorPage.Visible = True
        NavigatorButtons.Prior.Visible = True
        NavigatorButtons.Next.Visible = True
        NavigatorButtons.NextPage.Visible = True
        NavigatorButtons.Last.Visible = True
        NavigatorButtons.Insert.Visible = True
        NavigatorButtons.Delete.Visible = True
        NavigatorButtons.Edit.Visible = True
        NavigatorButtons.Post.Visible = True
        NavigatorButtons.Cancel.Visible = True
        NavigatorButtons.Refresh.Visible = True
        NavigatorButtons.SaveBookmark.Visible = True
        NavigatorButtons.GotoBookmark.Visible = True
        NavigatorButtons.Filter.Visible = True
        BackgroundBitmaps.Group.Data = {
          B62B0000424DB62B00000000000036000000280000004D000000300000000100
          180000000000802B0000D60E0000D60E00000000000000000000DDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCC
          CCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDD
          DDDDDDDDDDDDDDCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCC99BBBBBBCCCCCCCCCC99CCCCCCCCCC
          CC00DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCC
          CCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCC
          CCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBB
          BBBBCCCC99CCCCCCCCCC99CCCCCCBBBBBB00CCCCCCDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDD
          DDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBB
          BBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCC
          CCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCC00DDDDDDCCCCCC
          CCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          CCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCC99CCCC
          CC00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEE
          EEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBBBBBBBCCCC99
          BBBBBBCCCCCCBBBBBB00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEE
          EEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCCCCC99DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCBBBBBBBBBBBBCCCCCCBBBBBBCCCCCC00DDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCBBBBBBCCCCCCCCCC9900DDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEE
          DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEE
          EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCC
          CC00CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDD
          DDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCBBBBBB
          CCCCCCCCCCCCCCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBB
          BBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
          EEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCBBBBBBCCCCCCBBBBBBCCCC99CCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDCCCC
          CCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
          DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC99CCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCC00CCCCCCCCCCCC
          DDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEE
          DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCC
          CCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCBBBBBBCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCC
          CC00CCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCBBBBBB
          CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEE
          EEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDCCCCCCCCCCCCCCCCCC
          CCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBB
          BBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDD00CCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
          CCCCBBBBBBCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDD
          DDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCC
          CCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC00CCCCCCDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDD
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEE
          EEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDD
          DDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCC
          CCCCCCDDDDDDCCCC99CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEE
          EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDD
          DDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCC99CCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDD
          DD00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCC
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEE
          EEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDD
          DDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDD
          DDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEE
          EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC
          99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDDCCCCCCDDDDDDDDDD
          DDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDEEEEEEEEEEEEEEEE
          EEDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDD
          DDCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCC
          CCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDD
          DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC99CCCCCCCCCCCCCCCCCCCCCCCCDDDDDD
          CCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DD00DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBB
          BBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDD
          DDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCC
          CCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
          CCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDD00DDDDDDCCCCCCDDDDDDCCCCCCCCCC
          CCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDD
          DDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDD00CCCCCCCCCCCC
          CCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDD
          DDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
          DD00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCC
          CCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          DDDDDDDDDDDDCCCCCC00CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDD
          DDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
          DDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDD
          DDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCC00CCCCCCCCCCCCDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCDDDDDD
          DDDDDDDDDDDDCCCCCCDDDDDDCCCCCCBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDD
          DDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEE
          EEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCC00CCCCCCCCCCCC
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEE
          EEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCC
          CCCCDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBB
          BBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDD
          DDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CC00DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCDDDDDDCCCC
          CCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCCCCCCCCCC
          CCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
          DDDDDDEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCC
          CCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDCCCCCC00DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCC99CCCCCCCCCCCCDDDDDDDDDDDDEE
          EEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          CCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDD
          DDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDCCCCCC
          CCCCCCCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEE
          EEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDD
          DDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCC
          CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CC00CCCCCCDDDDDDCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCC
          DDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDD
          DDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCDD
          DDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCC
          CCCCCCCC99CCCCCCCCCCCCCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCBBBBBB
          CCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBB
          BBBBBBBBBBCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDD
          DDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDD
          DDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC
          CCDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00DDDDDDDDDDDDDDDDDDCCCCCCCCCC
          CCCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDD
          DDCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCC99CCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDCCCCCCBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCDDDD
          DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCDDDDDDCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEE
          EEEEDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCC
          BBBBBBCCCCCCBBBBBBCCCCCCBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          CC00DDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBBBBBBB
          CCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEE
          EEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDD
          DDDDCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE
          DDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCBBBBBBBBBBBBCCCCCCBBBBBBCCCCCCCCCCCCCCCCCCCCCCCC
          DDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDD
          DDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCDDDDDDDD
          DDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDDDDDD
          EEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDCCCCCCCCCCCCDDDD
          DDDDDDDDCCCCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD00DDDDDDDDDDDDEEEEEEEEEEEEDDDD
          DDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEDDDDDDEE
          EEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDD
          CCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCBBBBBBCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEDDDDDD00DDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDD
          DDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDD
          DDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCCCCC
          CCCCCCCCCCCCCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEE
          EE00DDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEEEEE
          EEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDD
          DDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDD
          DDDDDDEEEEEEDDDDDD00DDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEDD
          DDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDD
          DDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDD
          DDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDEEEE
          EEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCC
          CCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDDEEEEEEDDDDDDEEEE
          EEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
          DDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEE
          EEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDCCCCCCCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDEEEEEE00DDDDDDDDDDDD
          EEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDD
          DDDDDDDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCCCCCCCCCCCCCDDDDDDEEEEEEDDDD
          DDADDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDEEEEEEDDDD
          DDEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDD
          EEEEEEDDDDDDEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDEEEEEEDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDCCCCCCDDDDDDDDDDDDDDDDDD
          DDDDDDDDDDDDEEEEEEA4EEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDDDDDDDDD
          DDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDEEEEEE
          EEEEEEEEEEEEEEEEEEDDDDDDEEEEEEEEEEEEEEEEEEDDDDDDEEEEEEDDDDDDEEEE
          EEDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEE
          EEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCDDDDDDDDDDDDCCCCCCDDDDDDDD
          DDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE16EEEEEEEEEEEEEEEEEEEEEEEEDDDD
          DDDDDDDDDDDDDDDDDDDDEEEEEEDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDEEEEEE
          DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDD
          DDDDDDDDCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEE
          EEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE
          EEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCC
          CCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEE00}
        DataController.DataSource = ds_ypmx
        DataController.Summary.DefaultGroupSummaryItems = <>
        DataController.Summary.FooterSummaryItems = <>
        DataController.Summary.SummaryGroups = <
          item
            Links = <>
            SummaryItems = <>
          end>
        OptionsCustomize.ColumnFiltering = False
        OptionsCustomize.ColumnMoving = False
        OptionsData.CancelOnExit = False
        OptionsData.Deleting = False
        OptionsData.DeletingConfirmation = False
        OptionsData.Editing = False
        OptionsData.Inserting = False
        OptionsSelection.CellSelect = False
        OptionsSelection.MultiSelect = True
        OptionsView.GroupByBox = False
        object cxGridDBTableView3zyh: TcxGridDBColumn
          DataBinding.FieldName = 'zyh'
          Visible = False
          HeaderAlignmentHorz = taCenter
          Width = 132
        end
        object cxGridDBTableView3brxm: TcxGridDBColumn
          Caption = #30149#24202#21495
          DataBinding.FieldName = 'brxm'
          Visible = False
          GroupIndex = 0
          HeaderAlignmentHorz = taCenter
          SortIndex = 1
          SortOrder = soAscending
          Width = 228
        end
        object cxGridDBTableView3id: TcxGridDBColumn
          DataBinding.FieldName = 'id'
          Visible = False
          HeaderAlignmentHorz = taCenter
          Width = 84
          IsCaptionAssigned = True
        end
        object cxGridDBTableView3xmdm: TcxGridDBColumn
          Caption = #39033#30446#32534#30721
          DataBinding.FieldName = 'xmdm'
          HeaderAlignmentHorz = taCenter
          Width = 116
        end
        object cxGridDBTableView3xmmc: TcxGridDBColumn
          Caption = #39033#30446#21517#31216
          DataBinding.FieldName = 'xmmc'
          HeaderAlignmentHorz = taCenter
          Width = 230
        end
        object cxGridDBTableView3sl: TcxGridDBColumn
          Caption = #25968#37327
          DataBinding.FieldName = 'sl'
          HeaderAlignmentHorz = taCenter
          Width = 43
        end
        object cxGridDBTableView3ypgg: TcxGridDBColumn
          Caption = #33647#21697#35268#26684
          DataBinding.FieldName = 'ypgg'
          HeaderAlignmentHorz = taCenter
          Width = 148
        end
        object cxGridDBTableView3dw: TcxGridDBColumn
          Caption = #21333#20301
          DataBinding.FieldName = 'dw'
          HeaderAlignmentHorz = taCenter
          Width = 52
        end
        object cxGridDBTableView3ypyf: TcxGridDBColumn
          Caption = #29992#27861
          DataBinding.FieldName = 'ypyf'
          HeaderAlignmentHorz = taCenter
          Width = 47
        end
        object cxGridDBTableView3ypyl: TcxGridDBColumn
          Caption = #29992#37327
          DataBinding.FieldName = 'ypyl'
          HeaderAlignmentHorz = taCenter
          Width = 67
        end
        object cxGridDBTableView3yldw: TcxGridDBColumn
          DataBinding.FieldName = 'yldw'
          HeaderAlignmentHorz = taCenter
          Width = 40
          IsCaptionAssigned = True
        end
        object cxGridDBTableView3yytj: TcxGridDBColumn
          Caption = #29992#33647#36884#24452
          DataBinding.FieldName = 'yytj'
          Visible = False
          GroupIndex = 1
          HeaderAlignmentHorz = taCenter
          HeaderGlyphAlignmentVert = vaTop
          SortIndex = 0
          SortOrder = soAscending
          Width = 36
        end
      end
      object cxGridLevel3: TcxGridLevel
        GridView = cxGridDBTableView3
        Options.DetailFrameWidth = 0
      end
    end
    object rep_dryphz: TQuickRep
      Left = 64
      Top = 264
      Width = 794
      Height = 1123
      Frame.Color = clBlack
      Frame.DrawTop = False
      Frame.DrawBottom = False
      Frame.DrawLeft = False
      Frame.DrawRight = False
      DataSet = sp_ypmx
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = #23435#20307
      Font.Style = []
      Functions.Strings = (
        'PAGENUMBER'
        'COLUMNNUMBER'
        'REPORTTITLE')
      Functions.DATA = (
        '0'
        '0'
        #39#39)
      Options = [FirstPageHeader, LastPageFooter]
      Page.Columns = 1
      Page.Orientation = poPortrait
      Page.PaperSize = A4
      Page.Values = (
        100.000000000000000000
        2970.000000000000000000
        100.000000000000000000
        2100.000000000000000000
        100.000000000000000000
        100.000000000000000000
        0.000000000000000000)
      PrinterSettings.Copies = 1
      PrinterSettings.OutputBin = Auto
      PrinterSettings.Duplex = False
      PrinterSettings.FirstPage = 0
      PrinterSettings.LastPage = 0
      PrinterSettings.UseStandardprinter = False
      PrinterSettings.UseCustomBinCode = False
      PrinterSettings.CustomBinCode = 0
      PrinterSettings.ExtendedDuplex = 0
      PrinterSettings.UseCustomPaperCode = False
      PrinterSettings.CustomPaperCode = 0
      PrinterSettings.PrintMetaFile = False
      PrinterSettings.PrintQuality = 0
      PrinterSettings.Collate = 0
      PrinterSettings.ColorOption = 0
      PrintIfEmpty = True
      SnapToGrid = True
      Units = MM
      Zoom = 100
      PrevFormStyle = fsStayOnTop
      PreviewInitialState = wsMaximized
      PrevShowThumbs = False
      PrevShowSearch = False
      PrevInitialZoom = qrZoomToFit
      object DetailBand1: TQRBand
        Left = 38
        Top = 150
        Width = 718
        Height = 18
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        AlignToBottom = False
        Color = clWhite
        TransparentBand = False
        ForceNewColumn = False
        ForceNewPage = False
        Size.Values = (
          47.625000000000000000
          1899.708333333333000000)
        PreCaluculateBandHeight = False
        KeepOnOnePage = False
        BandType = rbDetail
        object QRDBText1: TQRDBText
          Left = 75
          Top = 1
          Width = 275
          Height = 15
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            39.687500000000000000
            198.437500000000000000
            2.645833333333333000
            727.604166666666800000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Color = clWhite
          DataSet = sp_ypmx
          DataField = 'xmmc'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRDBText5: TQRDBText
          Left = 398
          Top = 1
          Width = 131
          Height = 15
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            39.687500000000000000
            1053.041666666667000000
            2.645833333333333000
            346.604166666666700000)
          Alignment = taCenter
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Color = clWhite
          DataSet = sp_ypmx
          DataField = 'ypgg'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRDBText6: TQRDBText
          Left = 531
          Top = 1
          Width = 73
          Height = 15
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            39.687500000000000000
            1404.937500000000000000
            2.645833333333333000
            193.145833333333300000)
          Alignment = taCenter
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Color = clWhite
          DataSet = sp_ypmx
          DataField = 'ypyf'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRDBText7: TQRDBText
          Left = 606
          Top = 1
          Width = 37
          Height = 15
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            39.687500000000000000
            1603.375000000000000000
            2.645833333333333000
            97.895833333333340000)
          Alignment = taRightJustify
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Color = clWhite
          DataSet = sp_ypmx
          DataField = 'ypyl'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRDBText8: TQRDBText
          Left = 646
          Top = 1
          Width = 58
          Height = 15
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            39.687500000000000000
            1709.208333333333000000
            2.645833333333333000
            153.458333333333300000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Color = clWhite
          DataSet = sp_ypmx
          DataField = 'yldw'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRDBText9: TQRDBText
          Left = 2
          Top = 1
          Width = 71
          Height = 15
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            39.687500000000000000
            5.291666666666667000
            2.645833333333333000
            187.854166666666700000)
          Alignment = taCenter
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Color = clWhite
          DataSet = sp_ypmx
          DataField = 'yytj'
          Font.Charset = ANSI_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRDBText4: TQRDBText
          Left = 352
          Top = 1
          Width = 41
          Height = 15
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            39.687500000000000000
            931.333333333333500000
            2.645833333333333000
            108.479166666666700000)
          Alignment = taCenter
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Color = clWhite
          DataSet = sp_ypmx
          DataField = 'dw'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
      end
      object QRGroup2: TQRGroup
        Left = 38
        Top = 97
        Width = 718
        Height = 53
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        AlignToBottom = False
        Color = clWhite
        TransparentBand = False
        ForceNewColumn = False
        ForceNewPage = False
        Size.Values = (
          140.229166666666700000
          1899.708333333333000000)
        PreCaluculateBandHeight = False
        KeepOnOnePage = False
        Expression = 'sp_ypmx.zyh'
        FooterBand = QRBand1
        Master = rep_dryphz
        ReprintOnNewPage = False
        object QRLabel1: TQRLabel
          Left = 237
          Top = 8
          Width = 69
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            627.062500000000000000
            21.166666666666670000
            182.562500000000000000)
          Alignment = taCenter
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #29992#33647#26085#26399':'
          Color = clWhite
          Transparent = False
          WordWrap = True
          FontSize = 11
        end
        object QRDBText3: TQRDBText
          Left = 64
          Top = 8
          Width = 169
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            169.333333333333300000
            21.166666666666670000
            447.145833333333400000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Color = clWhite
          DataSet = sp_ypmx
          DataField = 'brxm'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -15
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 11
        end
        object QRShape3: TQRShape
          Left = 1
          Top = 24
          Width = 386
          Height = 4
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            10.583333333333330000
            2.645833333333333000
            63.500000000000000000
            1021.291666666667000000)
          Shape = qrsHorLine
          VertAdjust = 0
        end
        object QRLabel3: TQRLabel
          Left = 160
          Top = 32
          Width = 74
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            423.333333333333300000
            84.666666666666670000
            195.791666666666700000)
          Alignment = taCenter
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #33647' '#21697' '#21517' '#31216
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRLabel5: TQRLabel
          Left = 432
          Top = 32
          Width = 53
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            1143.000000000000000000
            84.666666666666670000
            140.229166666666700000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #33647#21697#35268#26684
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRLabel6: TQRLabel
          Left = 361
          Top = 32
          Width = 27
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            955.145833333333300000
            84.666666666666670000
            71.437500000000000000)
          Alignment = taCenter
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #21333#20301
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRShape4: TQRShape
          Left = 1
          Top = 48
          Width = 716
          Height = 4
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            10.583333333333330000
            2.645833333333333000
            127.000000000000000000
            1894.416666666667000000)
          Shape = qrsHorLine
          VertAdjust = 0
        end
        object QRLabel8: TQRLabel
          Left = 10
          Top = 32
          Width = 57
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            26.458333333333330000
            84.666666666666670000
            150.812500000000000000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #29992#33647#36884#24452
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = clNavy
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRLabel9: TQRLabel
          Left = 547
          Top = 32
          Width = 27
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            1447.270833333333000000
            84.666666666666670000
            71.437500000000000000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #29992#27861
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRLabel10: TQRLabel
          Left = 629
          Top = 32
          Width = 27
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            1664.229166666667000000
            84.666666666666670000
            71.437500000000000000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #29992#37327
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 10
        end
        object QRLabel4: TQRLabel
          Left = 8
          Top = 8
          Width = 54
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            21.166666666666670000
            21.166666666666670000
            142.875000000000000000)
          Alignment = taRightJustify
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #30149#24202#21495':'
          Color = clWhite
          Transparent = False
          WordWrap = True
          FontSize = 11
        end
        object QRLabel7: TQRLabel
          Left = 309
          Top = 8
          Width = 69
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            817.562500000000000000
            21.166666666666670000
            182.562500000000000000)
          Alignment = taCenter
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #29992#33647#26085#26399':'
          Color = clWhite
          Transparent = False
          WordWrap = True
          FontSize = 11
        end
      end
      object PageHeaderBand1: TQRBand
        Left = 38
        Top = 38
        Width = 718
        Height = 59
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        AlignToBottom = False
        Color = clWhite
        TransparentBand = False
        ForceNewColumn = False
        ForceNewPage = False
        Size.Values = (
          156.104166666666700000
          1899.708333333333000000)
        PreCaluculateBandHeight = False
        KeepOnOnePage = False
        BandType = rbPageHeader
        object QRLabel2: TQRLabel
          Left = 8
          Top = 5
          Width = 656
          Height = 22
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            58.208333333333340000
            21.166666666666670000
            13.229166666666670000
            1735.666666666667000000)
          Alignment = taCenter
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Caption = #30149#21306#24403#26085#21307#22065#25191#34892#21333
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = clNavy
          Font.Height = -21
          Font.Name = #23435#20307
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 16
        end
        object QRShape1: TQRShape
          Left = 218
          Top = 25
          Width = 235
          Height = 4
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            10.583333333333330000
            576.791666666666800000
            66.145833333333340000
            621.770833333333400000)
          Shape = qrsHorLine
          VertAdjust = 0
        end
        object QRShape2: TQRShape
          Left = 218
          Top = 28
          Width = 235
          Height = 4
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            10.583333333333330000
            576.791666666666800000
            74.083333333333340000
            621.770833333333400000)
          Shape = qrsHorLine
          VertAdjust = 0
        end
        object QRLabel11: TQRLabel
          Left = 40
          Top = 40
          Width = 69
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            105.833333333333300000
            105.833333333333300000
            182.562500000000000000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = True
          AutoStretch = False
          Caption = #30149#21306#21517#31216':'
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -15
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 11
        end
        object QRLabel12: TQRLabel
          Left = 112
          Top = 40
          Width = 233
          Height = 17
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            44.979166666666670000
            296.333333333333400000
            105.833333333333300000
            616.479166666666800000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Caption = #30149#21306#21517#31216':'
          Color = clWhite
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -15
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          WordWrap = True
          FontSize = 11
        end
        object QRExpr1: TQRExpr
          Left = 456
          Top = 40
          Width = 113
          Height = 16
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            42.333333333333340000
            1206.500000000000000000
            105.833333333333300000
            298.979166666666700000)
          Alignment = taRightJustify
          AlignToBand = False
          AutoSize = False
          AutoStretch = False
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          Color = clWhite
          ParentFont = False
          ResetAfterPrint = False
          Transparent = False
          WordWrap = True
          Expression = #39#31532#39'+STR(PAGENUMBER)+'#39#39029' '#25171#21360#26102#38388':'#39
          FontSize = 9
        end
        object QRShape5: TQRShape
          Left = 1
          Top = 55
          Width = 716
          Height = 4
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            10.583333333333330000
            2.645833333333333000
            145.520833333333300000
            1894.416666666667000000)
          Shape = qrsHorLine
          VertAdjust = 0
        end
        object QRSysData1: TQRSysData
          Left = 576
          Top = 40
          Width = 73
          Height = 16
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            42.333333333333330000
            1524.000000000000000000
            105.833333333333300000
            193.145833333333300000)
          Alignment = taLeftJustify
          AlignToBand = False
          AutoSize = True
          Color = clWhite
          Data = qrsDateTime
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = #23435#20307
          Font.Style = []
          ParentFont = False
          Transparent = False
          FontSize = 9
        end
      end
      object QRBand1: TQRBand
        Left = 38
        Top = 168
        Width = 718
        Height = 8
        Frame.Color = clBlack
        Frame.DrawTop = False
        Frame.DrawBottom = False
        Frame.DrawLeft = False
        Frame.DrawRight = False
        AlignToBottom = False
        Color = clWhite
        TransparentBand = False
        ForceNewColumn = False
        ForceNewPage = False
        Size.Values = (
          21.166666666666670000
          1899.708333333333000000)
        PreCaluculateBandHeight = False
        KeepOnOnePage = False
        BandType = rbGroupFooter
        object QRShape6: TQRShape
          Left = 1
          Top = -1
          Width = 716
          Height = 4
          Frame.Color = clBlack
          Frame.DrawTop = False
          Frame.DrawBottom = False
          Frame.DrawLeft = False
          Frame.DrawRight = False
          Size.Values = (
            10.583333333333330000
            2.645833333333333000
            -2.645833333333333000
            1894.416666666667000000)
          Shape = qrsHorLine
          VertAdjust = 0
        end
      end
    end
  end
  object sp_ypmx: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    ProcedureName = 'zybl_yzcx_dryzzxd;1'
    Parameters = <
      item
        Name = '@RETURN_VALUE'
        DataType = ftInteger
        Direction = pdReturnValue
        Precision = 10
        Value = 0
      end
      item
        Name = '@zyh'
        Attributes = [paNullable]
        DataType = ftString
        Size = 16
        Value = #39#39
      end
      item
        Name = '@yzsx'
        Attributes = [paNullable]
        DataType = ftString
        Size = 10
        Value = #39#39
      end>
    Left = 192
    Top = 152
    object sp_ypmxzyh: TStringField
      FieldName = 'zyh'
      FixedChar = True
      Size = 16
    end
    object sp_ypmxbrxm: TStringField
      FieldName = 'brxm'
      ReadOnly = True
      Size = 23
    end
    object sp_ypmxid: TAutoIncField
      FieldName = 'id'
      ReadOnly = True
    end
    object sp_ypmxxmdm: TStringField
      FieldName = 'xmdm'
      Size = 14
    end
    object sp_ypmxxmmc: TStringField
      FieldName = 'xmmc'
      Size = 100
    end
    object sp_ypmxsl: TIntegerField
      FieldName = 'sl'
    end
    object sp_ypmxypgg: TStringField
      FieldName = 'ypgg'
      FixedChar = True
      Size = 30
    end
    object sp_ypmxdw: TStringField
      FieldName = 'dw'
      ReadOnly = True
      Size = 10
    end
    object sp_ypmxypyf: TStringField
      FieldName = 'ypyf'
      FixedChar = True
      Size = 4
    end
    object sp_ypmxypyl: TStringField
      FieldName = 'ypyl'
      Size = 10
    end
    object sp_ypmxyldw: TStringField
      FieldName = 'yldw'
      Size = 10
    end
    object sp_ypmxyytj: TStringField
      FieldName = 'yytj'
      FixedChar = True
      Size = 4
    end
  end
  object ds_ypmx: TDataSource
    DataSet = sp_ypmx
    Left = 264
    Top = 152
  end
  object sp_brxx: TADOStoredProc
    Connection = DM_data.ado_mydata
    CursorType = ctStatic
    LockType = ltBatchOptimistic
    ProcedureName = 'zybl_cx_zybr;1'
    Parameters = <
      item
        Name = '@sr_ksdm'
        Attributes = [paNullable]
        DataType = ftString
        Size = 4
        Value = Null
      end>
    Left = 40
    Top = 88
  end
  object ds_brxx: TDataSource
    DataSet = sp_brxx
    Left = 112
    Top = 96
  end
end
