unit p_ypsjprint;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, QRCtrls, QuickRpt, ExtCtrls, DB, ADODB;

type
  Typsjprint = class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRLabel2: TQRLabel;
    QRBand1: TQRBand;
    QRLabel37: TQRLabel;
    QRSubDetail4: TQRSubDetail;
    QRLabel8: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRLabel41: TQRLabel;
    QRLabel7: TQRLabel;
    GroupHeaderBand2: TQRBand;
    QRLabel23: TQRLabel;
    PageFooterBand1: TQRBand;
    QRSysData1: TQRSysData;
    QRSubDetail1: TQRSubDetail;
    GroupHeaderBand3: TQRBand;
    QRLabel24: TQRLabel;
    GroupHeaderBand1: TQRBand;
    QRLabel5: TQRLabel;
    QRSubDetail2: TQRSubDetail;
    GroupFooterBand1: TQRBand;
    QRLabel40: TQRLabel;
    QRLabel47: TQRLabel;
    QRSubDetail3: TQRSubDetail;
    sjzy: TQRLabel;
    GroupFooterBand2: TQRBand;
    QRLabel43: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel54: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel57: TQRLabel;
    QRLabel59: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel60: TQRLabel;
    QRLabel62: TQRLabel;
    QRLabel64: TQRLabel;
    QRLabel66: TQRLabel;
    QRLabel55: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel26: TQRLabel;
    QRLabel44: TQRLabel;
    QRLabel56: TQRLabel;
    QRLabel58: TQRLabel;
    QRLabel61: TQRLabel;
    QRLabel63: TQRLabel;
    QRLabel65: TQRLabel;
    QRLabel67: TQRLabel;
    QRLabel27: TQRLabel;
    QRLabel68: TQRLabel;
    QRLabel69: TQRLabel;
    QRLabel71: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel15: TQRLabel;
    QRLabel16: TQRLabel;
    QRLabel28: TQRLabel;
    QRLabel29: TQRLabel;
    QRLabel30: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRLabel31: TQRLabel;
    QRLabel32: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel34: TQRLabel;
    QRLabel35: TQRLabel;
    QRLabel70: TQRLabel;
    QRLabel72: TQRLabel;
    QRLabel73: TQRLabel;
    QRLabel74: TQRLabel;
    QRLabel75: TQRLabel;
    QRLabel76: TQRLabel;
    QRLabel77: TQRLabel;
    QRLabel78: TQRLabel;
    QRLabel79: TQRLabel;
    QRShape4: TQRShape;
    QRShape9: TQRShape;
    QRShape5: TQRShape;
    QRShape6: TQRShape;
    QRShape7: TQRShape;
    QRShape8: TQRShape;
    QRLabel80: TQRLabel;
    QRLabel1: TQRLabel;
    QRLabel82: TQRLabel;
    QRLabel83: TQRLabel;
    QRLabel84: TQRLabel;
    QRLabel85: TQRLabel;
    QRLabel86: TQRLabel;
    QRLabel87: TQRLabel;
    QRLabel88: TQRLabel;
    QRLabel89: TQRLabel;
    QRLabel90: TQRLabel;
    QRLabel91: TQRLabel;
    QRLabel92: TQRLabel;
    QRLabel93: TQRLabel;
    QRLabel94: TQRLabel;
    QRLabel95: TQRLabel;
    QRLabel81: TQRLabel;
    spmc: TQRLabel;
    sccj: TQRLabel;
    scph: TQRLabel;
    yfyl: TQRLabel;
    kssj: TQRLabel;
    jssj: TQRLabel;
    yyyy: TQRLabel;
    qry_temp: TADOQuery;
    qry_tempid: TAutoIncField;
    qry_tempsjid: TStringField;
    qry_temppzwh: TStringField;
    qry_tempspmc: TStringField;
    qry_tempsccj: TStringField;
    qry_tempscph: TStringField;
    qry_tempyfyl: TStringField;
    qry_tempyykssj: TDateTimeField;
    qry_tempyyjssj: TDateTimeField;
    qry_tempyyyy: TStringField;
    spmc2: TQRLabel;
    sccj2: TQRLabel;
    scph2: TQRLabel;
    yfyl2: TQRLabel;
    kssj2: TQRLabel;
    jssj2: TQRLabel;
    yyyy2: TQRLabel;
    qry_temp2: TADOQuery;
    qry_temp2id: TAutoIncField;
    qry_temp2sjid: TStringField;
    qry_temp2pzwh: TStringField;
    qry_temp2spmc: TStringField;
    qry_temp2sccj: TStringField;
    qry_temp2scph: TStringField;
    qry_temp2yfyl: TStringField;
    qry_temp2yykssj: TDateTimeField;
    qry_temp2yyjssj: TDateTimeField;
    qry_temp2yyyy: TStringField;
    QRLabel36: TQRLabel;
    QRLabel38: TQRLabel;
    QRLabel39: TQRLabel;
    QRLabel42: TQRLabel;
    QRLabel45: TQRLabel;
    QRLabel46: TQRLabel;
    QRLabel48: TQRLabel;
    QRLabel49: TQRLabel;
    QRLabel50: TQRLabel;
    QRShape10: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRLabel97: TQRLabel;
    QRLabel98: TQRLabel;
    QRLabel53: TQRLabel;
    QRLabel51: TQRLabel;
    QRLabel99: TQRLabel;
    QRLabel52: TQRLabel;
    QRLabel100: TQRLabel;
    QRLabel101: TQRLabel;
    QRLabel102: TQRLabel;
    QRLabel103: TQRLabel;
    QRLabel104: TQRLabel;
    QRLabel105: TQRLabel;
    QRLabel106: TQRLabel;
    QRLabel107: TQRLabel;
    QRLabel108: TQRLabel;
    QRLabel109: TQRLabel;
    QRLabel110: TQRLabel;
    QRShape17: TQRShape;
    QRLabel111: TQRLabel;
    QRLabel112: TQRLabel;
    QRLabel113: TQRLabel;
    QRLabel114: TQRLabel;
    QRLabel115: TQRLabel;
    QRLabel116: TQRLabel;
    QRLabel117: TQRLabel;
    QRLabel118: TQRLabel;
    QRLabel119: TQRLabel;
    QRLabel120: TQRLabel;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRLabel121: TQRLabel;
    QRLabel122: TQRLabel;
    QRLabel123: TQRLabel;
    QRLabel124: TQRLabel;
    QRLabel125: TQRLabel;
    QRLabel126: TQRLabel;
    QRLabel127: TQRLabel;
    QRLabel128: TQRLabel;
    QRLabel129: TQRLabel;
    QRLabel130: TQRLabel;
    QRLabel131: TQRLabel;
    QRLabel132: TQRLabel;
    QRLabel133: TQRLabel;
    QRLabel134: TQRLabel;
    QRLabel135: TQRLabel;
    QRLabel136: TQRLabel;
    QRLabel137: TQRLabel;
    QRLabel138: TQRLabel;
    QRLabel139: TQRLabel;
    QRShape20: TQRShape;
    QRLabel140: TQRLabel;
    QRLabel141: TQRLabel;
    QRLabel142: TQRLabel;
    QRLabel143: TQRLabel;
    QRLabel144: TQRLabel;
    QRLabel145: TQRLabel;
    QRLabel146: TQRLabel;
    QRLabel147: TQRLabel;
    QRLabel148: TQRLabel;
    QRLabel149: TQRLabel;
    QRLabel150: TQRLabel;
    QRLabel151: TQRLabel;
    QRLabel152: TQRLabel;
    QRLabel153: TQRLabel;
    QRLabel154: TQRLabel;
    QRLabel155: TQRLabel;
    QRLabel156: TQRLabel;
    QRLabel157: TQRLabel;
    QRLabel158: TQRLabel;
    QRLabel159: TQRLabel;
    QRLabel160: TQRLabel;
    QRLabel161: TQRLabel;
    QRLabel162: TQRLabel;
    QRLabel175: TQRLabel;
    QRLabel176: TQRLabel;
    QRLabel177: TQRLabel;
    QRLabel178: TQRLabel;
    QRLabel179: TQRLabel;
    QRLabel180: TQRLabel;
    QRLabel181: TQRLabel;
    QRLabel182: TQRLabel;
    QRLabel183: TQRLabel;
    Shape2: TShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRLabel184: TQRLabel;
    QRLabel185: TQRLabel;
    QRLabel186: TQRLabel;
    QRLabel187: TQRLabel;
    Shape3: TShape;
    QRLabel188: TQRLabel;
    QRLabel189: TQRLabel;
    QRLabel190: TQRLabel;
    QRLabel191: TQRLabel;
    QRLabel192: TQRLabel;
    QRLabel193: TQRLabel;
    QRLabel194: TQRLabel;
    QRLabel195: TQRLabel;
    QRLabel196: TQRLabel;
    QRLabel197: TQRLabel;
    QRLabel198: TQRLabel;
    QRShape23: TQRShape;
    Shape5: TShape;
    Shape6: TShape;
    Shape7: TShape;
    QRLabel202: TQRLabel;
    QRLabel203: TQRLabel;
    QRLabel204: TQRLabel;
    QRLabel205: TQRLabel;
    QRLabel206: TQRLabel;
    QRLabel207: TQRLabel;
    QRShape24: TQRShape;
    QRLabel208: TQRLabel;
    QRLabel209: TQRLabel;
    QRLabel210: TQRLabel;
    QRLabel211: TQRLabel;
    QRLabel212: TQRLabel;
    QRLabel213: TQRLabel;
    QRLabel214: TQRLabel;
    QRLabel215: TQRLabel;
    QRLabel216: TQRLabel;
    QRLabel217: TQRLabel;
    QRLabel218: TQRLabel;
    QRLabel219: TQRLabel;
    QRLabel220: TQRLabel;
    QRLabel221: TQRLabel;
    QRLabel222: TQRLabel;
    QRSubDetail5: TQRSubDetail;
    bz: TQRLabel;
    GroupHeaderBand4: TQRBand;
    QRLabel223: TQRLabel;
    QRShape25: TQRShape;
    QRLabel20: TQRLabel;
    QRLabel96: TQRLabel;
    QRLabel164: TQRLabel;
    QRLabel163: TQRLabel;
    QRLabel165: TQRLabel;
    QRShape26: TQRShape;
    QRLabel166: TQRLabel;
    pzwh: TQRLabel;
    pzwh2: TQRLabel;
    procedure QRSubDetail1NeedData(Sender: TObject; var MoreData: Boolean);
    procedure QuickRep1BeforePrint(Sender: TCustomQuickRep;
      var PrintReport: Boolean);
    procedure QRSubDetail2NeedData(Sender: TObject; var MoreData: Boolean);
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
    hyyp_count:integer;
    byyp_count:integer;
  public
    { Public declarations }
  end;

var
  ypsjprint: Typsjprint;

implementation

{$R *.dfm}
uses p_blsj_ypsj,p_dm,p_func;

procedure Typsjprint.FormCreate(Sender: TObject);
begin
      QRLabel2.caption:=pub_yymc;
end;

procedure Typsjprint.QRSubDetail1NeedData(Sender: TObject;
  var MoreData: Boolean);
  var
  s,s1:string;
  i:integer;
begin
MoreData := True;
if  (qry_temp.eof) and (hyyp_count>=6) then
 MoreData := False ;
 spmc.caption:='';
 sccj.Caption:='';
 scph.Caption:='';
 kssj.Caption:='';
 jssj.Caption:='';
 yyyy.Caption:='';
 yfyl.Caption:='';
 pzwh.Caption:='';
 if not qry_temp.eof  then
 begin
 sccj.Caption:=qry_temp.FieldByName('sccj').asstring;
 spmc.Caption:=qry_temp.FieldByName('spmc').asstring;
 scph.Caption:=qry_temp.FieldByName('scph').asstring;
 yfyl.Caption:=qry_temp.FieldByName('yfyl').asstring;
 pzwh.Caption:=qry_temp.FieldByName('pzwh').asstring;
 s:=qry_temp.FieldByName('yykssj').asstring;
 //kssj.Caption:=Copy(s,1,length(s)-3);
 kssj.Caption:=Copy(s,1,17);
 s1:=qry_temp.FieldByName('yyjssj').asstring;
// jssj.Caption:=Copy(s1,1,length(s1)-3);
 jssj.Caption:=Copy(s1,1,17);
 yyyy.Caption:=qry_temp.FieldByName('yyyy').asstring;
 qry_temp.Next;
 end;
 if hyyp_count<6  then
 hyyp_count:=hyyp_count+1;
end;

procedure Typsjprint.QRSubDetail2NeedData(Sender: TObject;
  var MoreData: Boolean);
  var s,s1:string;
begin
 MoreData := True;
if (qry_temp2.eof) and (byyp_count>=6) then
 MoreData := False ;
 spmc2.caption:='';
 sccj2.Caption:='';
 scph2.Caption:='';
 kssj2.Caption:='';
 jssj2.Caption:='';
 yyyy2.Caption:='';
 yfyl2.Caption:='';
 pzwh2.Caption:='';
 if not qry_temp2.eof  then
 begin
 sccj2.Caption:=qry_temp2.FieldByName('sccj').asstring;
 spmc2.Caption:=qry_temp2.FieldByName('spmc').asstring;
 scph2.Caption:=qry_temp2.FieldByName('scph').asstring;
 yfyl2.Caption:=qry_temp2.FieldByName('yfyl').asstring;
 pzwh2.Caption:=qry_temp2.FieldByName('pzwh').asstring;
 pzwh2.Caption:=StringReplace(pzwh2.Caption,'¹úÒ©×¼×Ö', '', [rfReplaceAll]);
 s:=qry_temp2.FieldByName('yykssj').asstring;
 kssj2.Caption:=Copy(s,1,length(s)-3);
 s1:=qry_temp2.FieldByName('yyjssj').asstring;
 jssj2.Caption:=Copy(s1,1,length(s1)-3);
 yyyy2.Caption:=qry_temp2.FieldByName('yyyy').asstring;
 qry_temp2.Next;
 end;
 if byyp_count<6  then
 byyp_count:=byyp_count+1;
end;

procedure Typsjprint.QuickRep1BeforePrint(Sender: TCustomQuickRep;
  var PrintReport: Boolean);
var
id,ls,ls2:string;
begin
hyyp_count:=0;
byyp_count:=0;
id:=frm_ypsj.id;
ls:='select * from blsj_ypsj_hyyp where sjid='+#39+id+#39+' order by id';
qry_temp.Close;
qry_temp.SQL.Clear;
qry_temp.SQL.Add(ls);
qry_temp.Open;
hyyp_count:=qry_temp.RecordCount;
spmc.caption:='';
sccj.Caption:='';
scph.Caption:='';
kssj.Caption:='';
jssj.Caption:='';
yyyy.Caption:='';
yfyl.Caption:='';
qry_temp.First;
ls2:='select * from blsj_ypsj_byyp where sjid='+#39+id+#39+' order by id';
qry_temp2.Close;
qry_temp2.SQL.Clear;
qry_temp2.SQL.Add(ls2);
qry_temp2.Open;
byyp_count:=qry_temp2.RecordCount;
spmc2.caption:='';
sccj2.Caption:='';
scph2.Caption:='';
kssj2.Caption:='';
jssj2.Caption:='';
yyyy2.Caption:='';
yfyl2.Caption:='';
qry_temp2.First;
sjzy.Caption:=frm_ypsj.value1;
bz.Caption:=frm_ypsj.value2;
end;

end.
